GUROBI_VERSION_MAJOR=7
GUROBI_VERSION_MINOR=0
GUROBI_VERSION_REVISION=1
GUROBI_VERSION=${GUROBI_VERSION_MAJOR}.${GUROBI_VERSION_MINOR}.${GUROBI_VERSION_REVISION}
GUROBI_VERSION_SUFFIX=${GUROBI_VERSION_MAJOR}${GUROBI_VERSION_MINOR}
# set GUROBI_HOME according to your environment
GUROBI_HOME=/share/opt/x86_64_sl7/gurobi/linux64
