# specify your Gruobi version
GUROBI_VERSION_MAJOR=8
GUROBI_VERSION_MINOR=1
GUROBI_VERSION_REVISION=0
GUROBI_VERSION=${GUROBI_VERSION_MAJOR}.${GUROBI_VERSION_MINOR}.${GUROBI_VERSION_REVISION}
GUROBI_VERSION_SUFFIX=${GUROBI_VERSION_MAJOR}${GUROBI_VERSION_MINOR}
# set GUROBI_HOME according to your environment
GUROBI_HOME=/opt/gurobi
