# specify your Gruobi version
GUROBI_VERSION_MAJOR=7
GUROBI_VERSION_MINOR=5
GUROBI_VERSION_REVISION=2
GUROBI_VERSION=${GUROBI_VERSION_MAJOR}.${GUROBI_VERSION_MINOR}.${GUROBI_VERSION_REVISION}
GUROBI_VERSION_SUFFIX=${GUROBI_VERSION_MAJOR}${GUROBI_VERSION_MINOR}
# set GUROBI_HOME according to your environment
GUROBI_HOME=${HOME}/libs/gurobi/${GUROBI_VERSION}
