deregnet::LazyConstraintCallback Class Reference
Base lazy constraint callback class.
#include <LazyConstraintCallback.hpp>
Public Member Functions
LazyConstraintCallback (std::map< Node, GRBVar > *xx, Graph *xgraph, Node *xroot, double *xgap_cut)
Constructor passing data relevant for the callback.
Protected Member Functions
void callback ()
The actual callback function passed to the Gurobi optimizer.
Protected Attributes
std::map< Node, GRBVar > * x
Mapping from graph nodes to subgraph containment indicator variables.
Graph * graph
The underlying graph we are searching for subgraphs in.
Node * original_root
Root at beginning of the callback.
Node * root
Current root node.
std::vector< Node > selected_nodes
Current nodes in the subgraph.
double * gap_cut
Gap cut value.
Private Member Functions
virtual void get_solution_filter (NodeFilter &solution_filter)=0
Figure out the current solution.
virtual void set_lazy_constraint (const std::set< Node > &component, const std::set< Node > &global_parents)=0
Add lazy constraints to the model.
void check_and_set_lazy_constr (const int num_components, const InducedSubgraph::NodeMap< int > &component_map)
Check whether strong components violate any constraints and if so, add them.
bool get_component_nodes (const InducedSubgraph::NodeMap< int > &component_map, std::set< Node > &component, const int k)
Gets the nodes belonging to a strong component.
bool is_root_component (const std::set< Node > &component)
Check whether a component contains the root (no constraint violation possible in that case)
void get_parents (const std::set< Node > &component, std::set< Node > &parents, std::set< Node > &global_parents)
Find in-neighbors of a strong component within the subgraph and globally.
Detailed Description
Base lazy constraint callback class.
Implements most of the basic logic concerning lazy constraints. Specializations arise from whether there is a fixed root or not (see LazyConstraintCallbackRoot and LazyConstraintCallbackNoRoot) and/or whether variable groups have to be mapped with respect to reformulations of the original problem (see GrbfrcLazyConstraintCallbackRoot and GrbfrcLazyConstraintCallbackNoRoot).
Definition at line 60 of file LazyConstraintCallback.hpp.
Constructor & Destructor Documentation
LazyConstraintCallback()
deregnet::LazyConstraintCallback::LazyConstraintCallback (std::map< Node, GRBVar > * xx, Graph * xgraph, Node * xroot, double * xgap_cut)
Constructor passing data relevant for the callback.
Parameters
xx Mapping from graph nodes to subgraph containment indicator variables
xgraph Graph one is searching for subgraphs in
xroot The root node (or null if there is no fixed one)
xgap_cut The gap cut parameter
Definition at line 54 of file LazyConstraintCallback.cpp.
References gap_cut, graph, original_root, and root.
 : x { xx },
   graph { xgraph },
   original_root { xroot },
   root { nullptr },
   gap_cut { xgap_cut }
 {
    if (xroot) {
        root = new Node();
        *root = *original_root;
    }
 }
Member Function Documentation
callback()
void deregnet::LazyConstraintCallback::callback () [protected]
The actual callback function passed to the Gurobi optimizer.
Describe overall callback algorithm
Definition at line 70 of file LazyConstraintCallback.cpp.
References check_and_set_lazy_constr(), gap_cut, get_solution_filter(), graph, and selected_nodes.
                                      {
    try {
        if (where == GRB_CB_MIPSOL) { // new incumbent found
            NodeFilter solution_filter(*graph);
            selected_nodes = {};
            get_solution_filter(solution_filter);
            InducedSubgraph current_subgraph(*graph, solution_filter);
            InducedSubgraph::NodeMap<int> component_map(current_subgraph);
            int num_components { lemon::stronglyConnectedComponents(current_subgraph, component_map) };
            if (num_components > 1)
                check_and_set_lazy_constr(num_components, component_map);
        }
        else if (gap_cut && where == GRB_CB_MIP) {
            double best_objective { getDoubleInfo(GRB_CB_MIP_OBJBST) };
            double best_bound { getDoubleInfo(GRB_CB_MIP_OBJBND) };
            if (abs(best_objective - best_bound) < 0.000001) {}
            else if (abs(best_objective - best_bound) < (*gap_cut) * (1.0 + abs(best_objective)))
      {
                cout << "Achieved " << *gap_cut << " gap. Stopping optimization." << endl;
                abort();
            }
        }
    }
    catch (GRBException e) {
        std::cout << "Error number: " << e.getErrorCode() << std::endl;
        std::cout << e.getMessage() << std::endl;
    }
    catch (...) {
        std::cout << "Error during callback" << std::endl;
    }
}
check_and_set_lazy_constr()
void deregnet::LazyConstraintCallback::check_and_set_lazy_constr (const int num_components, const InducedSubgraph::NodeMap< int > & component_map) [private]
Check whether strong components violate any constraints and if so, add them.
Parameters
num_components Number of strong components in the current subgraph
component_map Data structure encoding connectivity of the subgraph, mapping nodes to component id's
Definition at line 101 of file LazyConstraintCallback.cpp.
References get_component_nodes(), get_parents(), is_root_component(), and set_lazy_constraint().
Referenced by callback().
                                                                                                         {
    for(int k = 0; k < num_components; k++) {
        std::set<Node> component;
        std::set<Node> parents;
        std::set<Node> global_parents;
        bool more_than_one_node = get_component_nodes(component_map, component, k); //
       violation of POLS
        if (!is_root_component(component) && more_than_one_node) {
            get_parents(component, parents, global_parents);
            if (parents.size() == 0)
                set_lazy_constraint(component, global_parents);
        }
    }
}
get_component_nodes()
bool deregnet::LazyConstraintCallback::get_component_nodes (const InducedSubgraph::NodeMap< int > & component_map, std::set< Node > & component, const int k) [private]
Gets the nodes belonging to a strong component.
Parameters
in component_map Data structure encoding connectivity of the subgraph, mapping nodes to components id's
out component Nodes in the component
in k Component id
Returns
Whether the component consists of more than one node
Definition at line 116 of file LazyConstraintCallback.cpp.
References selected_nodes.
Referenced by check_and_set_lazy_constr().
                                                              {
    for (auto v : selected_nodes)
        if (k == component_map[v])
            component.insert(v);
    if (component.size() > 1)
        return true;
    return false;
}
get_parents()
void deregnet::LazyConstraintCallback::get_parents (const std::set< Node > & component, std::set< Node > & parents, std::set< Node > & global_parents) [private]
Find in-neighbors of a strong component within the subgraph and globally.
Parameters
in component A strong component of the current subgraph
out parents Subgraph nodes (not in component) having edges connecting to a component node
out global_parents Any nodes (not in component) having edges connecting to a component node
Definition at line 134 of file LazyConstraintCallback.cpp.
References graph, INVALID, and selected_nodes.
Referenced by check_and_set_lazy_constr().
                                                                       {
    for (auto v : component) {
        for (InArcIt a(*graph, v); a != INVALID; ++a) {
            Node u = graph->source(a);
            if (component.find(u) == component.end()) {
                global_parents.insert(u);
                if (find(selected_nodes.begin(), selected_nodes.end(), u) !=
      selected_nodes.end())
                    parents.insert(u);
            }
        }
    }
}
get_solution_filter()
virtual void deregnet::LazyConstraintCallback::get_solution_filter (NodeFilter & solution_filter) [private], [pure virtual]
Figure out the current solution.
This depends on whether there is a fixed root. Correspondingly, conrete callback classed must implement this method in a suitable fashion.
Parameters
out solution_filter Boolean node map indicating nodes in current solution/subgraph
Implemented in deregnet::LazyConstraintCallbackNoRoot, and deregnet::LazyConstraintCallbackRoot.
Referenced by callback().
is_root_component()
bool deregnet::LazyConstraintCallback::is_root_component (const std::set< Node > & component) [private]
Check whether a component contains the root (no constraint violation possible in that case)
Parameters
component A strong component of the current subgraph
Returns
Whether the component contains the root
Definition at line 127 of file LazyConstraintCallback.cpp.
References root.
Referenced by check_and_set_lazy_constr().
                                                                            {
    for (auto v : component)
        if (v == *root)
            return true;
    return false;
}
set_lazy_constraint()
virtual void deregnet::LazyConstraintCallback::set_lazy_constraint (const std::set< Node > & component, const std::set< Node > & global_parents) [private], [pure virtual]
Add lazy constraints to the model.
Given a solution $G'=(V',E')$ and a strong component $S \subset V'$ such that for all nodes $u \in V' \backslash S $, if $(u,v) \in E'$ then $v \notin S$, we add some lazy constraints to the model. These constraints have a different mathematical form depending on whether the root is fixed or not and hence concrete callback classes must implement this method correspondingly.
Parameters
component An strong component of the solution not reachable from other nodes of the solution
global_parents All nodes not in the component which have a an edge towards a node from the component
Implemented in deregnet::LazyConstraintCallbackNoRoot, and deregnet::LazyConstraintCallbackRoot.
Referenced by check_and_set_lazy_constr().
Member Data Documentation
gap_cut
double* deregnet::LazyConstraintCallback::gap_cut [protected]
Gap cut value.
Definition at line 83 of file LazyConstraintCallback.hpp.
Referenced by callback(), and LazyConstraintCallback().
graph
Graph* deregnet::LazyConstraintCallback::graph [protected]
The underlying graph we are searching for subgraphs in.
Definition at line 79 of file LazyConstraintCallback.hpp.
Referenced by callback(), get_parents(), deregnet::LazyConstraintCallbackRoot::get_solution_filter(), deregnet::LazyConstraintCallbackNoRoot::get_solution_filter(), and LazyConstraintCallback().
original_root
Node* deregnet::LazyConstraintCallback::original_root [protected]
Root at beginning of the callback.
Definition at line 80 of file LazyConstraintCallback.hpp.
Referenced by LazyConstraintCallback().
root
Node* deregnet::LazyConstraintCallback::root [protected]
Current root node.
Definition at line 81 of file LazyConstraintCallback.hpp.
Referenced by deregnet::LazyConstraintCallbackNoRoot::get_solution_filter(), is_root_component(), and LazyConstraintCallback().
selected_nodes
std::vector<Node> deregnet::LazyConstraintCallback::selected_nodes [protected]
Current nodes in the subgraph.
Definition at line 82 of file LazyConstraintCallback.hpp.
Referenced by callback(), get_component_nodes(), get_parents(), deregnet::LazyConstraintCallbackRoot::get_solution_filter(), and deregnet::LazyConstraintCallbackNoRoot::get_solution_filter().
x
std::map<Node, GRBVar>* deregnet::LazyConstraintCallback::x [protected]
Mapping from graph nodes to subgraph containment indicator variables.
Definition at line 78 of file LazyConstraintCallback.hpp.
Referenced by deregnet::LazyConstraintCallbackRoot::get_solution_filter(), and deregnet::LazyConstraintCallbackNoRoot::get_solution_filter().
The documentation for this class was generated from the following files:
/datadisk/bbubu/home/self/bbubu/projects/deregnet/src/LazyConstraintCallback.hpp
/datadisk/bbubu/home/self/bbubu/projects/deregnet/src/LazyConstraintCallback.cpp