deregnet::AvgStartHeuristic Class Reference
Implementation of the heuristic solution algorithm for average DeRegNet algorithm.
#include <AvgStartHeuristic.hpp>
Public Member Functions
AvgStartHeuristic (Graph *xgraph, NodeMap< double > *xscore, Node *root, std::set< Node > *exclude, std::set< Node > *receptors, std::function< bool(double, double)> xcmp, int xmin_size, int xmax_size)
Private Member Functions
virtual Node * get_best_root () override
Find best node to add to solution in every iteration.
virtual bool search_further () override
Decide whether to continue searching further (for other solution than the one already found)
virtual bool feasible_node (Node *node) override
Decide whether adding a given node to the solution is feasible wrt the given constraints.
double update_avg (Node *node)
Private Attributes
int min_size
int max_size
double current_avg { 0.0 }
Additional Inherited Members
Detailed Description
Implementation of the heuristic solution algorithm for average DeRegNet algorithm.
Definition at line 49 of file AvgStartHeuristic.hpp.
Constructor & Destructor Documentation
AvgStartHeuristic()
deregnet::AvgStartHeuristic::AvgStartHeuristic (Graph * xgraph, NodeMap< double > * xscore, Node * root, std::set< Node > * exclude, std::set< Node > * receptors, std::function< bool(double, double)> xcmp, int xmin_size, int xmax_size)
Parameters
xgraph
xscore
root
exclude
receptors
xcmp
xmin_size
xmax_size
Definition at line 42 of file AvgStartHeuristic.cpp.
References max_size.
 : DeregnetStartHeuristic(xgraph, xscore, root,
      exclude, receptors, xcmp),
   min_size { xmin_size },
   max_size { xmax_size }
{ }
Member Function Documentation
feasible_node()
bool deregnet::AvgStartHeuristic::feasible_node (Node * node) [override], [private], [virtual]
Decide whether adding a given node to the solution is feasible wrt the given constraints.
Parameters
node A node in the graph
Returns
Whether adding the node is feasible
Implements deregnet::DeregnetStartHeuristic.
Definition at line 91 of file AvgStartHeuristic.cpp.
References current_avg, min_size, deregnet::DeregnetStartHeuristic::start_solution, and update_avg().
                                                {
    double new_avg { update_avg(node) };
    int current_size { static_cast<int>(start_solution->size()) };
    if (current_size >= min_size && new_avg < current_avg)
        return false;
    current_avg = new_avg;
    if (exclude) {
        if (start_solution->find(*node) == start_solution->end() &&
            exclude->find(*node) == exclude->end()) {
            return true;
        }
    }
    else
        if (start_solution->find(*node) == start_solution->end())
            return true;
    return false;
}
get_best_root()
Node * deregnet::AvgStartHeuristic::get_best_root () [override], [private], [virtual]
Find best node to add to solution in every iteration.
Returns
The best node to add
Implements deregnet::DeregnetStartHeuristic.
Definition at line 55 of file AvgStartHeuristic.cpp.
References deregnet::DeregnetStartHeuristic::graph, INVALID, and deregnet::DeregnetStartHeuristic::update_best_node().
                                       {
    double best;
    Node* best_node { nullptr };
    if (receptors)
        for (auto v : *receptors)
            update_best_node(&best_node, &v, &best);
    else
        for (NodeIt v(*graph); v != INVALID; ++v)
            update_best_node(&best_node, &v, &best);
    return best_node;
}
search_further()
bool deregnet::AvgStartHeuristic::search_further () [override], [private], [virtual]
Decide whether to continue searching further (for other solution than the one already found)
Returns
Whether to search further
Implements deregnet::DeregnetStartHeuristic.
Definition at line 68 of file AvgStartHeuristic.cpp.
References deregnet::DeregnetStartHeuristic::found_node, max_size, min_size, deregnet::DeregnetStartHeuristic::start_solution, and deregnet::DeregnetStartHeuristic::success.
                                       {
    int current_size { static_cast<int>(start_solution->size()) };
    if (current_size < min_size) {
        if (found_node)
            return true;
        else
            return false;
    }
    if (current_size >= min_size && current_size < max_size) {
        if (found_node)
            return true;
        else {
            success = true;
            return false;
        }
    }
    if (current_size == max_size) {
        success = true;
        return false;
    }
    return false; // to get rid of compiler warning ... ;)
}
update_avg()
double deregnet::AvgStartHeuristic::update_avg (Node * node) [private]
Definition at line 109 of file AvgStartHeuristic.cpp.
References current_avg, deregnet::DeregnetStartHeuristic::score, and deregnet::DeregnetStartHeuristic::start_solution.
Referenced by feasible_node().
                                               {
    int current_size { static_cast<int>(start_solution->size()) };
    return ((*score)[*node] + current_size * current_avg) / (current_size + 1);
}
Member Data Documentation
current_avg
double deregnet::AvgStartHeuristic::current_avg { 0.0 } [private]
Definition at line 55 of file AvgStartHeuristic.hpp.
Referenced by feasible_node(), and update_avg().
max_size
int deregnet::AvgStartHeuristic::max_size [private]
Definition at line 54 of file AvgStartHeuristic.hpp.
Referenced by AvgStartHeuristic(), and search_further().
min_size
int deregnet::AvgStartHeuristic::min_size [private]
Definition at line 53 of file AvgStartHeuristic.hpp.
Referenced by feasible_node(), and search_further().
The documentation for this class was generated from the following files:
/datadisk/bbubu/home/self/bbubu/projects/deregnet/src/AvgStartHeuristic.hpp
/datadisk/bbubu/home/self/bbubu/projects/deregnet/src/AvgStartHeuristic.cpp