grbfrc::CharnesCooper Class Reference
#include <CharnesCooper.h>
Public Member Functions
CharnesCooper (FMILP &fmipRef)
void printInvalidity ()
void transform ()
GRBModel getTransform ()
void solveTransform ()
void solveTransform (GRBCallback &callback)
void run (int time_limit)
void run (GRBCallback &callback, int time_limit)
void writeSolution ()
FMILPSol getSolution ()
Private Member Functions
void backTransformSolution ()
int getIndex (GRBVar &var)
Private Attributes
FMILP * fmip
FMILPSol solution
bool invalid
bool transformed
GRBModel transformation
GRBVar t
std::vector< GRBVar * > y
Detailed Description
Definition at line 48 of file CharnesCooper.h.
Constructor & Destructor Documentation
grbfrc::CharnesCooper::CharnesCooper (FMILP & fmipRef)
Definition at line 11 of file CharnesCooper.cpp.
References grbfrc::FMILP::baseModel, fmip, invalid, grbfrc::FMILP::isFLP(), printInvalidity(), transformation, transformed, and grbfrc::FMILP::update().
             : fmip { &fmipRef },
               transformed { false },
               transformation { GRBModel((fmip->baseModel)->getEnv()) }
 {
  if (!fmip->isFLP()) { printInvalidity(); invalid = true; }
  else { invalid = false; fmip->update(); }
 }
Member Function Documentation
void grbfrc::CharnesCooper::backTransformSolution () [private]
Definition at line 184 of file CharnesCooper.cpp.
References fmip, grbfrc::FMILP::get(), grbfrc::FMILPSol::objVal, solution, t, transformation, grbfrc::FMILPSol::varVals, and y.
Referenced by run().
 {
  int status { transformation.get(GRB_IntAttr_Status) };
  if (status == GRB_OPTIMAL)
   {
    solution.objVal = transformation.get(GRB_DoubleAttr_ObjVal);
    double tvalue { t.get(GRB_DoubleAttr_X) };
    for (int i = 0; i < fmip->get(GRB_IntAttr_NumVars); i++)
     {
      double value { y[i]->get(GRB_DoubleAttr_X) };
      solution.varVals.push_back(value / tvalue);
     }
   }
  else std::cout << "GRB_Status : " << transformation.get(GRB_IntAttr_Status) << std::endl;
 }
int grbfrc::CharnesCooper::getIndex (GRBVar & var) [private]
Definition at line 200 of file CharnesCooper.cpp.
References fmip, grbfrc::FMILP::get(), and grbfrc::FMILP::vars.
Referenced by transform().
 {
  for (int i = 0; i < fmip->get(GRB_IntAttr_NumVars); i++)
    if (var.sameAs(*(fmip->vars[i]))) return i;
  return -1;
 }
FMILPSol grbfrc::CharnesCooper::getSolution ()
Definition at line 179 of file CharnesCooper.cpp.
References solution.
 {
  return solution;
 }
GRBModel grbfrc::CharnesCooper::getTransform ()
Definition at line 89 of file CharnesCooper.cpp.
References invalid, printInvalidity(), transform(), transformation, and transformed.
Referenced by grbfrc::FMILP::getCharnesCooperTransform().
 {
  if (invalid)
   {
    printInvalidity();
    return transformation;
   }
  else if (transformed) return transformation;
  else
   {
    transform();
    return transformation;
   }
 }
void grbfrc::CharnesCooper::printInvalidity ()
Definition at line 20 of file CharnesCooper.cpp.
Referenced by CharnesCooper(), getTransform(), run(), and solveTransform().
 {
   std::cout << "\n!!! === Not a FLP === !!!\n\n";
 }
void grbfrc::CharnesCooper::run (int time_limit)
Definition at line 147 of file CharnesCooper.cpp.
References backTransformSolution(), invalid, printInvalidity(), solveTransform(), transform(), and transformed.
Referenced by grbfrc::FMILP::runCharnesCooper().
 {
  if (invalid) printInvalidity();
  else
   {
    std::cout << "\n=========== solving FLP via Charnes-Cooper transform ===========\n\n";
    if (!transformed) transform();
    solveTransform();
    backTransformSolution();
   }
 }
void grbfrc::CharnesCooper::run (GRBCallback & callback, int time_limit)
Definition at line 159 of file CharnesCooper.cpp.
References backTransformSolution(), invalid, printInvalidity(), solveTransform(), transform(), and transformed.
 {
  if (invalid) printInvalidity();
  else
   {
    std::cout << "\n=========== solving FLP via Charnes-Cooper transform ===========\n\n";
    if (!transformed) transform();
    solveTransform(callback);
    backTransformSolution();
   }
 }
void grbfrc::CharnesCooper::solveTransform ()
Definition at line 104 of file CharnesCooper.cpp.
References invalid, printInvalidity(), and transformation.
Referenced by run().
 {
  if (invalid) printInvalidity();
  else
   {
    try
     {
      transformation.optimize();
      std::cout << std::endl;
     }
    catch (GRBException e)
     {
      std::cout << "Gurobi error: " << e.getMessage() << "\n\n";
     }
    catch (...)
     {
      std::cout << "Error while attempting to optimize transform ... \n\n";
     }
   }
 }
void grbfrc::CharnesCooper::solveTransform (GRBCallback & callback)
Definition at line 125 of file CharnesCooper.cpp.
References invalid, printInvalidity(), and transformation.
 {
  if (invalid) printInvalidity();
  else
   {
    try
     {
      transformation.setCallback(&callback);
      transformation.optimize();
      std::cout << std::endl;
     }
    catch (GRBException e)
     {
      std::cout << "Gurobi error: " << e.getMessage() << "\n\n";
     }
    catch (...)
     {
      std::cout << "Error while attempting to optimize transform ... \n\n";
     }
   }
 }
void grbfrc::CharnesCooper::transform ()
Definition at line 25 of file CharnesCooper.cpp.
References grbfrc::FMILPObj::denominator, fmip, grbfrc::FMILP::get(), grbfrc::FMILP::getConstrs(), getIndex(), grbfrc::FMILP::getRow(), grbfrc::FMILPObj::numerator, grbfrc::FMILP::objective, grbfrc::FMILPObj::sense, t, transformation, grbfrc::FMILP::vars, and y.
Referenced by getTransform(), and run().
 {
  // create t variable corr. to t = 1/(ex + f) // set objective to max {cy + dt} //
  t = transformation.addVar(0.0, GRB_INFINITY, 0.0, GRB_CONTINUOUS, "t");
  // create y variables corr. to y = tx //
  for (auto var : fmip->vars) {
        y.push_back(new GRBVar(transformation.addVar(-GRB_INFINITY, GRB_INFINITY, 0.0,
      GRB_CONTINUOUS)));
        transformation.update();
        double lb { var->get(GRB_DoubleAttr_LB) };
        double ub { var->get(GRB_DoubleAttr_UB) };
        transformation.addConstr(*(y.back()) - lb*t >= 0.0);
        transformation.addConstr(*(y.back()) - ub*t <= 0.0);
  }
  transformation.update();
  // objective of the FLP: max (cx + d)/(ex + f) //
  FMILPObj& objective = fmip->objective;
  GRBLinExpr& objNumerator = objective.numerator;
  double d { objNumerator.getConstant() };
  GRBLinExpr& objDenominator = objective.denominator;
  double f { objDenominator.getConstant() };
  int objSense = objective.sense;
  // set objective of transform to cy + dt
  GRBLinExpr transformObj { d * t };
  for (unsigned int i = 0; i < objNumerator.size(); i++)
   {
    GRBVar var = objNumerator.getVar(i);
    int j = getIndex(var);
    double coeff = objNumerator.getCoeff(i);
    transformObj += coeff * (*y[j]);
   }
  transformation.setObjective(transformObj, objSense);
  // add ey + ft == 1 constraint //
  GRBLinExpr lhs { f * t };
  for (unsigned int i = 0; i < objDenominator.size(); i++)
   {
    GRBVar var = objDenominator.getVar(i);
    int j = getIndex(var);
    double coeff = objDenominator.getCoeff(i);
    lhs += coeff * (*y[j]);
   }
  transformation.addConstr(lhs, GRB_EQUAL, 1.0);
  // constraints of the FLP: Ax {<=,=,>=} b //
  GRBConstr* constrs { fmip->getConstrs() };
  int numConstrs { fmip->get(GRB_IntAttr_NumConstrs) };
  // add Ay - bt {<=,=,>=} 0 constraints //
  for (int i = 0; i < numConstrs; i++)
   {
    GRBLinExpr origLhs { fmip->getRow(*constrs) };
    double b { constrs->get(GRB_DoubleAttr_RHS) };
    lhs = - b * t ;
    for (unsigned int i = 0; i < origLhs.size(); i++)
     {
      GRBVar var = origLhs.getVar(i);
      int j = getIndex(var);
      double coeff = origLhs.getCoeff(i);
      lhs += coeff * (*y[j]);
     }
    char constrSense { constrs->get(GRB_CharAttr_Sense) };
    transformation.addConstr(lhs, constrSense, 0.0);
    constrs++;
   }
  transformation.update();
 }
void grbfrc::CharnesCooper::writeSolution ()
Definition at line 171 of file CharnesCooper.cpp.
References fmip, solution, and grbfrc::FMILP::solution.
Referenced by grbfrc::FMILP::runCharnesCooper().
 {
  if (fmip->solution) *(fmip->solution) = solution;
  else if (!fmip->solution) fmip->solution = new FMILPSol(
      solution);
  else std::cout << "No solution avaiable!" << std::endl;
 }
Member Data Documentation
FMILP* grbfrc::CharnesCooper::fmip [private]
Definition at line 52 of file CharnesCooper.h.
Referenced by backTransformSolution(), CharnesCooper(), getIndex(), transform(), and writeSolution().
bool grbfrc::CharnesCooper::invalid [private]
Definition at line 54 of file CharnesCooper.h.
Referenced by CharnesCooper(), getTransform(), run(), and solveTransform().
FMILPSol grbfrc::CharnesCooper::solution [private]
Definition at line 53 of file CharnesCooper.h.
Referenced by backTransformSolution(), getSolution(), and writeSolution().
GRBVar grbfrc::CharnesCooper::t [private]
Definition at line 57 of file CharnesCooper.h.
Referenced by backTransformSolution(), and transform().
GRBModel grbfrc::CharnesCooper::transformation [private]
Definition at line 56 of file CharnesCooper.h.
Referenced by backTransformSolution(), CharnesCooper(), getTransform(), solveTransform(), and transform().
bool grbfrc::CharnesCooper::transformed [private]
Definition at line 55 of file CharnesCooper.h.
Referenced by CharnesCooper(), getTransform(), and run().
std::vector<GRBVar*> grbfrc::CharnesCooper::y [private]
Definition at line 58 of file CharnesCooper.h.
Referenced by backTransformSolution(), and transform().
The documentation for this class was generated from the following files:
/home/sebastian/wrk/deregnet/deregnet/grbfrc/include/grbfrc/CharnesCooper.h
/home/sebastian/wrk/deregnet/deregnet/grbfrc/src/CharnesCooper.cpp