grbfrc::Dinkelbach Class Reference
#include <Dinkelbach.h>
Public Member Functions
Dinkelbach (FMILP &fmipRef, double qi, int maxit, int maxsec, double tolerance)
void set_q_init (double qi)
void set_max_iter (int max)
void set_time_limit (int seconds)
void set_tolerance (double tolerance)
void run (bool verbose=true, bool logFile=true, std::string logFileName=`grbfrc.log`)
void run (GRBCallback &callback, bool verbose=true, bool logFile=true, std::string logFileName=`grbfrc.log`)
void writeSolution ()
FMILPSol getSolution ()
Private Member Functions
void registerSolution (double objVal, FMILP *fmip)
void printProblem (int status, int iter)
void printIteration (int iter)
Private Attributes
FMILP * fmip
double q_init { 0.0 }
int max_iter { 30 }
int time_limit { 3600 }
double tol { 0.0001 }
FMILPSol solution
Detailed Description
Definition at line 46 of file Dinkelbach.h.
Constructor & Destructor Documentation
grbfrc::Dinkelbach::Dinkelbach (FMILP & fmipRef, double qi, int maxit, int maxsec, double tolerance)
Definition at line 12 of file Dinkelbach.cpp.
References max_iter, q_init, time_limit, and tol.
                     : fmip { &fmipRef },
                       q_init { qi },
                       max_iter { maxit },
                       time_limit { maxsec },
                       tol { tolerance }
                    { }
Member Function Documentation
FMILPSol grbfrc::Dinkelbach::getSolution ()
Definition at line 173 of file Dinkelbach.cpp.
References solution.
 { return solution; }
void grbfrc::Dinkelbach::printIteration (int iter) [private]
Definition at line 183 of file Dinkelbach.cpp.
Referenced by run().
     {
      std::cout << "\n==================== Dinkelbach iteration "
                << iter << " ===================\n\n";
     }
void grbfrc::Dinkelbach::printProblem (int status, int iter) [private]
Definition at line 176 of file Dinkelbach.cpp.
Referenced by run().
     {
      std::cout << "\nModel iteration " << iter
                << " is not solvable, GRB_STATUS: " << status << "\n";
     }
void grbfrc::Dinkelbach::registerSolution (double objVal, FMILP * fmip) [private]
void grbfrc::Dinkelbach::run (bool verbose = true, bool logFile = true, std::string logFileName = `grbfrc.log`)
Definition at line 36 of file Dinkelbach.cpp.
References grbfrc::FMILP::baseModel, grbfrc::FMILPObj::denominator, fmip, max_iter, grbfrc::FMILPObj::numerator, grbfrc::FMILP::objective, grbfrc::FMILPSol::objVal, printIteration(), printProblem(), q_init, grbfrc::FMILPObj::sense, solution, tol, grbfrc::FMILP::vars, and grbfrc::FMILPSol::varVals.
Referenced by grbfrc::FMILP::runDinkelbach().
 {
  // set verbosity and logging behaviour ============================================== //
  if (verbose)
   { std::cout << "\n============ Solving FMILP with Dinkelbach's algorithm ============\n"; }
  else
   { ((fmip->baseModel)->getEnv()).set(GRB_IntParam_LogToConsole, 0); }
  if (logFile)
   { ((fmip->baseModel)->getEnv()).set(GRB_StringParam_LogFile, logFileName); }
  else
   { ((fmip->baseModel)->getEnv()).set(GRB_StringParam_LogFile, ""); }
  // get model data =================================================================== //
  GRBModel* model = fmip->baseModel;
  FMILPObj& objective = fmip->objective;
  GRBLinExpr& objNumerator = objective.numerator;
  GRBLinExpr& objDenominator = objective.denominator;
  int sense = objective.sense;
  // algorithm parameters ============================================================= //
  int iter = 0;
  double q { q_init };
  double Fq;
  bool done { false };
  // solve Dinkelbach iterations ====================================================== //
  double sign { 1.0 };
  if (sense == GRB_MINIMIZE) { sign = -1.0; }
  while (!done && iter < max_iter)
   {
    iter++;
    if (verbose) { printIteration(iter); }
    GRBLinExpr currentObj = sign * objNumerator - q * objDenominator;
    model->setObjective(currentObj, GRB_MAXIMIZE);
    model->optimize();
    int status = model->get(GRB_IntAttr_Status);
    if (status != GRB_OPTIMAL) { printProblem(status, iter); }
    else
     {
      Fq = model->get(GRB_DoubleAttr_ObjVal);
      double numVal { sign * objNumerator.getValue() };
      double denomVal { objDenominator.getValue() };
      q = numVal / denomVal;
      std::cout << "\n q = " << q
                << " , |F(q)| = " << std::abs(Fq) << std::endl;
      if (std::abs(Fq) < tol)
       {
        done = true;
        if (sense == GRB_MINIMIZE) { q = -q; }
        // register solution
        solution.objVal = q;
        for (unsigned int i = 0; i < (fmip->vars).size(); i++)
          solution.varVals.push_back(((fmip->vars)[i])->get(GRB_DoubleAttr_X));
       }
     }
   }
 }
void grbfrc::Dinkelbach::run (GRBCallback & callback, bool verbose = true, bool logFile = true, std::string logFileName = `grbfrc.log`)
Definition at line 100 of file Dinkelbach.cpp.
References grbfrc::FMILP::baseModel, grbfrc::FMILPObj::denominator, fmip, max_iter, grbfrc::FMILPObj::numerator, grbfrc::FMILP::objective, grbfrc::FMILPSol::objVal, printIteration(), printProblem(), q_init, grbfrc::FMILPObj::sense, solution, tol, grbfrc::FMILP::vars, and grbfrc::FMILPSol::varVals.
 {
  // set verbosity and logging behaviour ============================================== //
  if (verbose)
   { std::cout << "\n============ Solving FMILP with Dinkelbach's algorithm ============\n"; }
  else
   { ((fmip->baseModel)->getEnv()).set(GRB_IntParam_LogToConsole, 0); }
  if (logFile)
   { ((fmip->baseModel)->getEnv()).set(GRB_StringParam_LogFile, logFileName); }
  else
   { ((fmip->baseModel)->getEnv()).set(GRB_StringParam_LogFile, ""); }
  // get model data =================================================================== //
  GRBModel* model = fmip->baseModel;
  FMILPObj& objective = fmip->objective;
  GRBLinExpr& objNumerator = objective.numerator;
  GRBLinExpr& objDenominator = objective.denominator;
  int sense = objective.sense;
  // algorithm parameters ============================================================= //
  int iter = 0;
  double q { q_init };
  double Fq;
  bool done { false };
  // solve Dinkelbach iterations ====================================================== //
  double sign { 1.0 };
  if (sense == GRB_MINIMIZE) { sign = -1.0; }
  while (!done && iter < max_iter)
   {
    iter++;
    if (verbose) { printIteration(iter); }
    GRBLinExpr currentObj = sign * objNumerator - q * objDenominator;
    model->setObjective(currentObj, GRB_MAXIMIZE);
    model->setCallback(&callback);
    model->optimize();
    int status = model->get(GRB_IntAttr_Status);
    if (status != GRB_OPTIMAL) { printProblem(status, iter); }
    else
     {
      Fq = model->get(GRB_DoubleAttr_ObjVal);
      double numVal { sign * objNumerator.getValue() };
      double denomVal { objDenominator.getValue() };
      q = numVal / denomVal;
      std::cout << "\n q = " << q
                << " , |F(q)| = " << std::abs(Fq) << std::endl;
      if (std::abs(Fq) < tol)
       {
        done = true;
        if (sense == GRB_MINIMIZE) { q = -q; }
        // register solution
        solution.objVal = q;
        for (unsigned int i = 0; i < (fmip->vars).size(); i++)
          solution.varVals.push_back(((fmip->vars)[i])->get(GRB_DoubleAttr_X));
       }
     }
   }
 }
void grbfrc::Dinkelbach::set_max_iter (int max)
Definition at line 27 of file Dinkelbach.cpp.
References max_iter.
 { max_iter = max; }
void grbfrc::Dinkelbach::set_q_init (double qi)
Definition at line 24 of file Dinkelbach.cpp.
References q_init.
 { q_init = qi; }
void grbfrc::Dinkelbach::set_time_limit (int seconds)
Definition at line 30 of file Dinkelbach.cpp.
References time_limit.
 { time_limit = seconds; }
void grbfrc::Dinkelbach::set_tolerance (double tolerance)
Definition at line 33 of file Dinkelbach.cpp.
References tol.
 { tol = tolerance; }
void grbfrc::Dinkelbach::writeSolution ()
Definition at line 166 of file Dinkelbach.cpp.
References fmip, solution, and grbfrc::FMILP::solution.
Referenced by grbfrc::FMILP::runDinkelbach().
 {
  if (fmip->solution) *(fmip->solution) = solution;
  else if (!fmip->solution) fmip->solution = new FMILPSol(
      solution);
  else std::cout << "No solution avaiable!" << std::endl;
 }
Member Data Documentation
FMILP* grbfrc::Dinkelbach::fmip [private]
Definition at line 50 of file Dinkelbach.h.
Referenced by run(), and writeSolution().
int grbfrc::Dinkelbach::max_iter { 30 } [private]
Definition at line 52 of file Dinkelbach.h.
Referenced by Dinkelbach(), run(), and set_max_iter().
double grbfrc::Dinkelbach::q_init { 0.0 } [private]
Definition at line 51 of file Dinkelbach.h.
Referenced by Dinkelbach(), run(), and set_q_init().
FMILPSol grbfrc::Dinkelbach::solution [private]
Definition at line 55 of file Dinkelbach.h.
Referenced by getSolution(), run(), and writeSolution().
int grbfrc::Dinkelbach::time_limit { 3600 } [private]
Definition at line 53 of file Dinkelbach.h.
Referenced by Dinkelbach(), and set_time_limit().
double grbfrc::Dinkelbach::tol { 0.0001 } [private]
Definition at line 54 of file Dinkelbach.h.
Referenced by Dinkelbach(), run(), and set_tolerance().
The documentation for this class was generated from the following files:
/home/sebastian/wrk/deregnet/deregnet/grbfrc/include/grbfrc/Dinkelbach.h
/home/sebastian/wrk/deregnet/deregnet/grbfrc/src/Dinkelbach.cpp