deregnet::DeregnetFinder< ModelType, Data > Class Template Reference
Main entry point for running DeRegNet algorithms.
#include <DeregnetFinder.hpp>
Public Member Functions
DeregnetFinder (Data *xdata)
Constructor, taking the relevant data as argument.
std::vector< Subgraph > run ()
Method which finds the subgraphs.
void find_start_solution (std::pair< Node, std::set< Node >> **start_solution)
Finds a heuristic optimal start solution.
void find_suboptimal_start_solution (std::pair< Node, std::set< Node >> **start_solution, std::set< std::string > *nodes_so_far)
Finds a heuristic suboptimal start solution.
Subgraph to_subgraph (Solution solution, std::string signature)
Transform a solution from the Solution type to the Subgraph type.
template<>
void find_start_solution (std::pair< Node, std::set< Node >> **start_solution)
template<>
void find_start_solution (std::pair< Node, std::set< Node >> **start_solution)
template<>
void find_suboptimal_start_solution (std::pair< Node, std::set< Node >> **start_solution, std::set< std::string > *nodes_so_far)
template<>
void find_suboptimal_start_solution (std::pair< Node, std::set< Node >> **start_solution, std::set< std::string > *nodes_so_far)
Private Member Functions
void run_optimal_init (std::pair< Node, std::set< Node >> **start_solution)
Preparation for finding the optimal subgraph.
void run_suboptimal_init (std::pair< Node, std::set< Node > > **start_solution, std::set< std::string > *nodes_so_far)
Perparation for finding suboptimal subgraphs.
void run_optimal_windup (bool solve_successful, std::vector< Subgraph > *subgraphs)
Post-processing after attempt to find optimal subgraph.
bool run_suboptimal_windup (bool solve_successful, std::vector< Subgraph > *subgraphs, std::set< std::string > *nodes_so_far, int i)
Post-processing after attempt to find suboptimal subgraphs.
Private Attributes
Data * data
Pointer to DeregnetData, i.e. DrgntData or AvgdrgntData.
DeregnetModel< ModelType, Data > * model
Model instance to be build and solved.
Detailed Description
template<typename ModelType, typename Data>
class deregnet::DeregnetFinder< ModelType, Data >
Main entry point for running DeRegNet algorithms.
DeregnetFinder has two template paramters: 1) ModelType, referring to either GRBModel or grbfrc::FMILP, 2) Data, referring to a type representing algorithm data suitable for the ModelType parameter. In case of ModelType = GRBModel, Data should be DrgntData, in case of ModelType = grbfrc::FMILP, Data should be AvgdrgntData.
Todo
Todo This desgin seems not very optimal and somehow flawed. The most straight-forward improvment would be to implement the absolute version of the algorithm, i.e. ModelType = GRBModel, in terms of grbfrc::FMILP. ModelType would go away and Data could specfiy which algorithm to run, for example.
Todo
Todo More refined logging system.
Author
Sebastian Winkler
Definition at line 81 of file DeregnetFinder.hpp.
Constructor & Destructor Documentation
DeregnetFinder()
template<typename ModelType , typename Data >
deregnet::DeregnetFinder< ModelType, Data >::DeregnetFinder (Data * xdata)
Constructor, taking the relevant data as argument.
A DeregnetFinder object is instantiated by passing a pointer to a suitable Data object. In case of ModelType = GRBModel, this data object should be of type DrgntData, in case of ModelType = grbfrc::FMILP, it should be of type AvgdrngtData. (Having to state this here is most likely expression of a design flaw. As long as you do as just specfified, it works though and otherwise the code will presumably not compile anyhow. But having to match the two template parameters manually feels wrong.)
Parameters
in xdata Pointer to suitable DeregnetData object. If ModelType = GRBModel, you have to pass a pointer to a DrgntData object, in case of ModelType = grbfrc::FMILP, you have to pass a pointer to a AvgdrgntData object.
Definition at line 166 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::model.
 : data { xdata },
   model { new DeregnetModel<ModelType, Data>(xdata) }
{ }
Member Function Documentation
find_start_solution() [1/3]
template<typename ModelType, typename Data>
void deregnet::DeregnetFinder< ModelType, Data >::find_start_solution (std::pair< Node, std::set< Node >> ** start_solution)
Finds a heuristic optimal start solution.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run_optimal_init().
find_start_solution() [2/3]
template<>
void deregnet::DeregnetFinder< GRBModel, DrgntData >::find_start_solution (std::pair< Node, std::set< Node >> ** start_solution) [inline]
Definition at line 318 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetData::exclude, deregnet::DeregnetData::graph, deregnet::DeregnetData::model_sense, deregnet::DeregnetData::receptors, deregnet::DeregnetData::root, and deregnet::DeregnetData::score.
                                                                                              {
    std::function<bool(double, double)> cmp;
    // Adjust comparison function based on whether to minimize or maximize
    if (data->model_sense == "min") cmp = std::greater<double>();
    else cmp = std::less<double>();
    // Try to find start solution and when successful register it
    StartHeuristic heuristic(data->graph,
                             data->score,
                             data->root,
                             data->exclude,
                             data->receptors,
                             cmp,
                             data->size);
    if (heuristic.run())
        *start_solution = heuristic.getStartSolution();
}
find_start_solution() [3/3]
template<>
void deregnet::DeregnetFinder< FMILP, AvgdrgntData >::find_start_solution (std::pair< Node, std::set< Node >> ** start_solution) [inline]
Definition at line 338 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetData::exclude, deregnet::DeregnetData::graph, deregnet::AvgdrgntData::max_size, deregnet::AvgdrgntData::min_size, deregnet::DeregnetData::model_sense, deregnet::DeregnetData::receptors, deregnet::DeregnetData::root, and deregnet::DeregnetData::score.
                                                                                              {
    std::function<bool(double, double)> cmp;
    // Adjust comparison function based on whether to minimize or maximize
    if (data->model_sense == "min") cmp = std::greater<double>();
    else cmp = std::less<double>();
    // Try to find start solution and when successful register it
    AvgStartHeuristic heuristic(data->graph,
                                data->score,
                                data->root,
                                data->exclude,
                                data->receptors,
                                cmp,
                                data->min_size,
                                data->max_size);
    if (heuristic.run())
        *start_solution = heuristic.getStartSolution();
}
find_suboptimal_start_solution() [1/3]
template<typename ModelType, typename Data>
void deregnet::DeregnetFinder< ModelType, Data >::find_suboptimal_start_solution (std::pair< Node, std::set< Node >> ** start_solution, std::set< std::string > * nodes_so_far)
Finds a heuristic suboptimal start solution.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_init().
find_suboptimal_start_solution() [2/3]
template<>
void deregnet::DeregnetFinder< GRBModel, DrgntData >::find_suboptimal_start_solution (std::pair< Node, std::set< Node >> ** start_solution, std::set< std::string > * nodes_so_far) [inline]
Definition at line 364 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetData::exclude, deregnet::DeregnetData::graph, deregnet::DeregnetData::max_overlap, deregnet::DeregnetData::model_sense, deregnet::DeregnetData::nodeid, deregnet::DeregnetData::receptors, deregnet::DeregnetData::root, and deregnet::DeregnetData::score.
                                                                                                          {
    std::function<bool(double, double)> cmp;
    // Adjust comparison function based on whether to minimize or maximize
    if (data->model_sense == "min") cmp = std::greater<double>();
    else cmp = std::less<double>();
    // Try to find start solution and when successful register it
    SuboptimalStartHeuristic heuristic(data->graph,
                                       data->score,
                                       data->root,
                                       data->exclude,
                                       data->receptors,
                                       cmp,
                                       data->nodeid,
                                       nodes_so_far,
                                       data->max_overlap,
                                       data->size);
    if (heuristic.run())
        *start_solution = heuristic.getStartSolution();
}
find_suboptimal_start_solution() [3/3]
template<>
void deregnet::DeregnetFinder< FMILP, AvgdrgntData >::find_suboptimal_start_solution (std::pair< Node, std::set< Node >> ** start_solution, std::set< std::string > * nodes_so_far) [inline]
Definition at line 387 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetData::exclude, deregnet::DeregnetData::graph, deregnet::DeregnetData::max_overlap, deregnet::AvgdrgntData::max_size, deregnet::AvgdrgntData::min_size, deregnet::DeregnetData::model_sense, deregnet::DeregnetData::nodeid, deregnet::DeregnetData::receptors, deregnet::DeregnetData::root, and deregnet::DeregnetData::score.
                                                                                                          {
    std::function<bool(double, double)> cmp;
    // Adjust comparison function based on whether to minimize or maximize
    if (data->model_sense == "min") cmp = std::greater<double>();
    else cmp = std::less<double>();
    // Try to find start solution and when successful register it
    AvgSuboptimalStartHeuristic heuristic(data->graph,
                                          data->score,
                                          data->root,
                                          data->exclude,
                                          data->receptors,
                                          cmp,
                                          data->nodeid,
                                          nodes_so_far,
                                          data->max_overlap,
                                          data->min_size,
                                          data->max_size);
    if (heuristic.run())
        *start_solution = heuristic.getStartSolution();
}
run()
template<typename ModelType , typename Data >
std::vector< Subgraph > deregnet::DeregnetFinder< ModelType, Data >::run ()
Method which finds the subgraphs.
This method finds subgraphs as specified on instantiation of the DeregnetFinder instance. You get back a vector with the subgraphs.
Returns
Vector containing the the subgraphs
Definition at line 252 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetFinder< ModelType, Data >::model, deregnet::DeregnetData::num_subopt_iter, deregnet::DeregnetFinder< ModelType, Data >::run_optimal_init(), deregnet::DeregnetFinder< ModelType, Data >::run_optimal_windup(), deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_init(), and deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_windup().
Referenced by main().
                                                         {
    std::pair<Node, std::set<Node>>* start_solution { nullptr }; // potential heuristic start solution
    // find optimal subgraph
    run_optimal_init(&start_solution); // construct model,
       etc.
/*
    std::ofstream file;
    file.open("heuristic_start.nodes");
    for (auto v : start_solution->second)
        file << (*data->nodeid)[v] << "\n";
    file.close();
*/
    std::vector<Subgraph> subgraphs; // data structure for found subgraphs
    bool solve_successful { model->solve(start_solution) }; // try to find optimal solution
    run_optimal_windup(solve_successful, &subgraphs); // handle result of
       optimal solution attempt
    // find suboptimal subgraphs
    std::set<std::string> nodes_so_far { subgraphs.back().nodes }; // tracking nodes contained in some
       already found subgraph
    for (int i = 0; i < data->num_subopt_iter; ++i) {
        start_solution = nullptr; // reset to NULL ... Where does the
       previous one go? Memory leak?
        run_suboptimal_init(&start_solution, &nodes_so_far); // adapt model for
       finding next suboptimal, etc.
        solve_successful = model->solve(start_solution); // try to find next suboptimal
       solution
        if (!run_suboptimal_windup(solve_successful, &subgraphs, &nodes_so_far, i))
         // once no suboptimal subgraph could be found, do not try again ;)
            break;
    }
    return subgraphs;
}
run_optimal_init()
template<typename ModelType, typename Data>
void deregnet::DeregnetFinder< ModelType, Data >::run_optimal_init (std::pair< Node, std::set< Node >> ** start_solution) [private]
Preparation for finding the optimal subgraph.
Definition at line 173 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetData::exclude, deregnet::DeregnetFinder< ModelType, Data >::find_start_solution(), deregnet::DeregnetData::include, deregnet::DeregnetFinder< ModelType, Data >::model, deregnet::DeregnetData::receptors, deregnet::DeregnetData::root, deregnet::DeregnetData::start_heuristic, and deregnet::DeregnetData::terminals.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run().
                                                                                                    {
    model->createVariables(); // create binary variables corresponding to the nodes
    model->addBaseConstraints(); // add base constraints to the model, ie connectivity etc.
    // add optional constraints (ie. include, exclude, receptor and/or terminal constraints)
    if (data->include)
        model->addIncludeConstraints(); // which nodes to include in the subgraph, no matter what
    if (data->exclude)
        model->addExcludeConstraints(); // which nodes to exclude from the subgraph, no matter what
    if (data->receptors && !data->root)
        model->addReceptorConstraints(); // how to handle nodes which are 'receptors'
    if (data->terminals)
        model->addTerminalConstraints(); // how to handle nodes which are 'temrinals'
    // optionally find heuristic start solution by greedy algorithm
    if (data->start_heuristic)
        find_start_solution(start_solution);
    // in case a heuristic start solution was specfied but none was found, issue a warning.
    // TODO: not necessarily always to std::cout ...
    if (data->start_heuristic && !(*start_solution))
        std::cout << "No heuristic start solution found.\n" << std::endl;
}
run_optimal_windup()
template<typename ModelType , typename Data >
void deregnet::DeregnetFinder< ModelType, Data >::run_optimal_windup (bool solve_successful, std::vector< Subgraph > * subgraphs) [private]
Post-processing after attempt to find optimal subgraph.
Definition at line 196 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::model, NO_OPTIMAL_SUBGRAPH_FOUND, and deregnet::DeregnetFinder< ModelType, Data >::to_subgraph().
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run().
                                                                                                           
         {
    // if a solution was found update subgraphs data structure
    if (solve_successful) {
        subgraphs->push_back (to_subgraph(model->getCurrentSolution(), "optimal"));
    }
    // if no solution was found, issue a message and end the program
    // TODO: not necessarily always to std::cerr
    // TODO: exit normally and handle issue in normal program flow?
    else {
        std::cerr << "No optimal subgraph could be found." << std::endl;
        exit(NO_OPTIMAL_SUBGRAPH_FOUND);
    }
}
run_suboptimal_init()
template<typename ModelType , typename Data >
void deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_init (std::pair< Node, std::set< Node > > ** start_solution, std::set< std::string > * nodes_so_far) [private]
Perparation for finding suboptimal subgraphs.
Definition at line 212 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::DeregnetFinder< ModelType, Data >::find_suboptimal_start_solution(), deregnet::DeregnetFinder< ModelType, Data >::model, and deregnet::DeregnetData::start_heuristic.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run().
                                                                                           {
    // make sure only a certain fraction of nodes contained in some already found subgraph
    // will be contained this subgraph
    model->addSuboptimalityConstraint(*nodes_so_far);
    // optionally find heuristic start solution by greedy algorithm
    if (data->start_heuristic)
        find_suboptimal_start_solution(start_solution, nodes_so_far);
    // in case a heuristic start solution was specfied but none was found, issue a warning.
    // TODO: not necessarily always to std::cout ...
    if (data->start_heuristic && !(*start_solution))
        std::cout << "No heuristic start solution found.\n" << std::endl;
}
run_suboptimal_windup()
template<typename ModelType , typename Data >
bool deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_windup (bool solve_successful, std::vector< Subgraph > * subgraphs, std::set< std::string > * nodes_so_far, int i) [private]
Post-processing after attempt to find suboptimal subgraphs.
Definition at line 228 of file DeregnetFinder.hpp.
References deregnet::DeregnetFinder< ModelType, Data >::model, deregnet::Solution::nodes, and deregnet::DeregnetFinder< ModelType, Data >::to_subgraph().
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run().
                                                                   {
    // if a solution was found update subgraphs data structure
    // Also, update the data structure tracking nodes contained in any already found subgraph
    if (solve_successful) {
        Solution current = model->getCurrentSolution() ;
        subgraphs->push_back(to_subgraph(current, "suboptimal_" + std::to_string(i)));
        for (auto node: current.nodes)
            nodes_so_far->insert(node);
        return true;
    }
    // if no solution was found, issue a message
    // TODO: not necessarily always to std::cout
    else {
        std::cout << "With these parameters, no more than " << i
                  << " suboptimal subgraphs could be found." << std::endl;
        return false;
    }
}
to_subgraph()
template<typename ModelType , typename Data >
Subgraph deregnet::DeregnetFinder< ModelType, Data >::to_subgraph (Solution solution, std::string signature)
Transform a solution from the Solution type to the Subgraph type.
Definition at line 280 of file DeregnetFinder.hpp.
References deregnet::Solution::avg_score, deregnet::Subgraph::avg_score, deregnet::DeregnetFinder< ModelType, Data >::data, deregnet::Solution::edgelist, deregnet::Subgraph::edgelist, deregnet::getNodeById(), deregnet::DeregnetData::nodeid, deregnet::Solution::nodes, deregnet::Subgraph::nodes, deregnet::DeregnetData::original_graph, deregnet::DeregnetData::receptor_as_root, deregnet::DeregnetData::receptors, deregnet::Subgraph::receptors, deregnet::Solution::rootid, deregnet::Subgraph::rootid, deregnet::Subgraph::signature, deregnet::DeregnetData::terminals, deregnet::Subgraph::terminals, deregnet::Solution::total_score, and deregnet::Subgraph::total_score.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::run_optimal_windup(), and deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_windup().
                                                                                            {
    Subgraph subgraph;
    subgraph.signature = signature;
    subgraph.rootid = solution.rootid;
    subgraph.nodes = solution.nodes;
    subgraph.total_score = solution.total_score;
    subgraph.avg_score = solution.avg_score;
    if (!data->receptor_as_root)
        swap(data->receptors, data->terminals);
    if (data->receptors)
        for (auto nodeid : subgraph.nodes) {
            Node node;
            if (getNodeById(data->original_graph,
      data->nodeid, nodeid, &node))
                if (data->receptors->find(node) != data->
      receptors->end())
                    subgraph.receptors.insert(nodeid);
        }
    if (data->terminals)
        for (auto nodeid : subgraph.nodes) {
            Node node;
            if (getNodeById(data->original_graph,
      data->nodeid, nodeid, &node))
                if (data->terminals->find(node) != data->
      terminals->end())
                    subgraph.terminals.insert(nodeid);
        }
    if (!data->receptor_as_root)
        for (auto edge : solution.edgelist)
            subgraph.edgelist.insert(std::make_pair(edge.second, edge.first));
    else
        subgraph.edgelist = solution.edgelist;
    return subgraph;
}
Member Data Documentation
data
template<typename ModelType, typename Data>
Data* deregnet::DeregnetFinder< ModelType, Data >::data [private]
Pointer to DeregnetData, i.e. DrgntData or AvgdrgntData.
Definition at line 85 of file DeregnetFinder.hpp.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::find_start_solution(), deregnet::DeregnetFinder< ModelType, Data >::find_suboptimal_start_solution(), deregnet::DeregnetFinder< ModelType, Data >::run(), deregnet::DeregnetFinder< ModelType, Data >::run_optimal_init(), deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_init(), and deregnet::DeregnetFinder< ModelType, Data >::to_subgraph().
model
template<typename ModelType, typename Data>
DeregnetModel<ModelType, Data>* deregnet::DeregnetFinder< ModelType, Data >::model [private]
Model instance to be build and solved.
Definition at line 86 of file DeregnetFinder.hpp.
Referenced by deregnet::DeregnetFinder< ModelType, Data >::DeregnetFinder(), deregnet::DeregnetFinder< ModelType, Data >::run(), deregnet::DeregnetFinder< ModelType, Data >::run_optimal_init(), deregnet::DeregnetFinder< ModelType, Data >::run_optimal_windup(), deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_init(), and deregnet::DeregnetFinder< ModelType, Data >::run_suboptimal_windup().
The documentation for this class was generated from the following file:
/datadisk/bbubu/home/self/bbubu/projects/deregnet/src/DeregnetFinder.hpp