deregnet::DeregnetModel< Model, Data > Class Template Reference
#include <DeregnetModel.h>
Public Member Functions
DeregnetModel (Data *data)
void createVariables ()
void addBaseConstraints ()
void addIncludeConstraints ()
void addExcludeConstraints ()
void addReceptorConstraints ()
void addTerminalConstraints ()
bool solve (std::pair< Node, std::set< Node >> *start_solution)
void addSuboptimalityConstraint (std::set< std::string > &nodes_so_far)
Solution getCurrentSolution ()
template<>
void addSuboptimalityConstraint (std::set< std::string > &nodes_so_far)
template<>
void addSuboptimalityConstraint (std::set< std::string > &nodes_so_far)
template<>
bool solve (std::pair< Node, std::set< Node >> *start_solution)
template<>
bool solve (std::pair< Node, std::set< Node >> *start_solution)
Protected Attributes
GRBEnv env
Model model { Model(env) }
std::map< Node, GRBVar > x
std::map< Node, GRBVar > * y { nullptr }
Data * data
Graph * graph
NodeMap< double > * score
NodeMap< std::string > * nodeid
Node * root
Private Member Functions
void createVariablesRoot ()
void createVariablesNoRoot ()
void addBaseConstraintsRoot ()
void addBaseConstraintsNoRoot ()
void setStartSolution (std::pair< Node, std::set< Node >> *start_solution)
void setup_solve (std::pair< Node, std::set< Node >> *start_solution)
void setCallbackRoot ()
void setCallbackNoRoot ()
void _getCurrentSolution (std::string *rootid, std::set< Node > *nodes, Solution *solution)
GRBLinExpr setBaseConstraintsRootCommon ()
GRBLinExpr setBaseConstraintsNoRootCommon ()
template<>
void addBaseConstraintsRoot ()
template<>
void addBaseConstraintsNoRoot ()
template<>
void addBaseConstraintsRoot ()
template<>
void addBaseConstraintsNoRoot ()
template<>
void createVariablesRoot ()
template<>
void createVariablesRoot ()
template<>
void createVariablesNoRoot ()
template<>
void createVariablesNoRoot ()
template<>
void setStartSolution (std::pair< Node, std::set< Node >> *start_solution)
template<>
void setStartSolution (std::pair< Node, std::set< Node >> *start_solution)
template<>
void setCallbackRoot ()
template<>
void setCallbackRoot ()
template<>
void setCallbackNoRoot ()
template<>
void setCallbackNoRoot ()
template<>
void _getCurrentSolution (std::string *rootid, std::set< Node > *nodes, Solution *solution)
template<>
void _getCurrentSolution (std::string *rootid, std::set< Node > *nodes, Solution *solution)
Detailed Description
template<typename Model, typename Data>
*
class deregnet::DeregnetModel< Model, Data >
Definition at line 62 of file DeregnetModel.h.
Constructor & Destructor Documentation
template<typename Model , typename Data> deregnet::DeregnetModel< Model, Data >::DeregnetModel (Data * data)
Definition at line 109 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, deregnet::DeregnetModel< Model, Data >::nodeid, deregnet::DeregnetModel< Model, Data >::root, and deregnet::DeregnetModel< Model, Data >::score.
 : data { xdata },
   graph { xdata->graph },
   score { xdata->score },
   nodeid { xdata->nodeid },
   root { xdata->root }
{ }
Member Function Documentation
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::_getCurrentSolution (std::string * rootid, std::set< Node > * nodes, Solution * solution) [private]
Referenced by deregnet::DeregnetModel< Model, Data >::getCurrentSolution().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::_getCurrentSolution (std::string * rootid, std::set< Node > * nodes, Solution * solution) [inline], [private]
Definition at line 426 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::nodeid, deregnet::Solution::nodes, deregnet::DeregnetModel< Model, Data >::root, deregnet::Solution::total_score, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                                                                           
                  {
    for (NodeIt v(*graph); v != INVALID; ++v) {
        if (x[v].get(GRB_DoubleAttr_X) >= 0.98) {
            nodes->insert(v);
            (solution->nodes).insert((*nodeid)[v]);
            if (!root) {
                if ((*y)[v].get(GRB_DoubleAttr_X) >= 0.98)
                    *rootid = (*nodeid)[v];
            }
            else
                *rootid = (*nodeid)[*root];
        }
    }
    solution->total_score = model.get(GRB_DoubleAttr_ObjVal);
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::_getCurrentSolution (std::string * rootid, std::set< Node > * nodes, Solution * solution) [inline], [private]
Definition at line 443 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::nodeid, deregnet::Solution::nodes, deregnet::DeregnetModel< Model, Data >::root, deregnet::Solution::total_score, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                                                                           
                        {
    for (NodeIt v(*graph); v != INVALID; ++v) {
        if (model.getVal(x[v]) >= 0.98) {
            nodes->insert(v);
            (solution->nodes).insert((*nodeid)[v]);
            if (!root) {
                if (model.getVal((*y)[v]) >= 0.98)
                    *rootid = (*nodeid)[v];
            }
            else
                *rootid = (*nodeid)[*root];
        }
    }
    solution->total_score = model.getObjVal() * nodes->size();
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::addBaseConstraints ()
Definition at line 127 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::addBaseConstraintsNoRoot(), deregnet::DeregnetModel< Model, Data >::addBaseConstraintsRoot(), deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::root.
                                                    {
    if (root)
        addBaseConstraintsRoot();
    else
        addBaseConstraintsNoRoot();
    model.update();
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::addBaseConstraintsNoRoot () [private]
Referenced by deregnet::DeregnetModel< Model, Data >::addBaseConstraints().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::addBaseConstraintsNoRoot () [inline], [private]
Definition at line 174 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon().
                                                                  {
    GRBLinExpr subgraph_size_lhs { setBaseConstraintsNoRootCommon() };
    model.addConstr(subgraph_size_lhs == data->size);
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::addBaseConstraintsNoRoot () [inline], [private]
Definition at line 187 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::AvgdrgntData::min_size, deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon().
                                                                        {
    GRBLinExpr subgraph_size_lhs { setBaseConstraintsNoRootCommon() };
    model.addConstr(data->min_size <= subgraph_size_lhs);
    model.addConstr(subgraph_size_lhs <= data->max_size);
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::addBaseConstraintsRoot () [private]
Referenced by deregnet::DeregnetModel< Model, Data >::addBaseConstraints().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::addBaseConstraintsRoot () [inline], [private]
Definition at line 168 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon().
                                                                {
    GRBLinExpr subgraph_size_lhs { setBaseConstraintsRootCommon() };
    model.addConstr(subgraph_size_lhs == data->size);
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::addBaseConstraintsRoot () [inline], [private]
Definition at line 180 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::AvgdrgntData::min_size, deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon().
                                                                      {
    GRBLinExpr subgraph_size_lhs { setBaseConstraintsRootCommon() };
    model.addConstr(data->min_size <= subgraph_size_lhs);
    model.addConstr(subgraph_size_lhs <= data->max_size);
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::addExcludeConstraints ()
Definition at line 201 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetData::exclude, deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::x.
                                                       {
    for (Node v : *(data->exclude))
        model.addConstr(x[v] == 0);
    model.update();
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::addIncludeConstraints ()
Definition at line 194 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetData::include, deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::x.
                                                       {
    for (Node v : *(data->include))
        model.addConstr(x[v] == 1);
    model.update();
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::addReceptorConstraints ()
Definition at line 208 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetData::receptors, deregnet::DeregnetModel< Model, Data >::root, and deregnet::DeregnetModel< Model, Data >::y.
                                                        {
    if (!root) {
        std::set<Node>* receptors { data->receptors };
        for (NodeIt v(*graph); v != INVALID; ++v)
            if (receptors->find(v) == receptors->end())
                model.addConstr((*y)[v] == 0);
    }
    model.update();
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::addSuboptimalityConstraint (std::set< std::string > & nodes_so_far)
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::addSuboptimalityConstraint (std::set< std::string > & nodes_so_far) [inline]
Definition at line 308 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::nodeid, and deregnet::DeregnetModel< Model, Data >::x.
                                                                                                   {
    GRBLinExpr nodes_so_far_expr;
    for (NodeIt v(*graph); v != INVALID; ++v) {
        if (nodes_so_far.find((*nodeid)[v]) != nodes_so_far.end())
            nodes_so_far_expr += x[v];
    }
    model.addConstr(nodes_so_far_expr <= data->max_overlap * data->size);
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::addSuboptimalityConstraint (std::set< std::string > & nodes_so_far) [inline]
Definition at line 318 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::nodeid, and deregnet::DeregnetModel< Model, Data >::x.
                                                                                                         {
    GRBLinExpr nodes_so_far_expr;
    GRBLinExpr size_expr;
    for (NodeIt v(*graph); v != INVALID; ++v) {
        size_expr += x[v];
        if (nodes_so_far.find((*nodeid)[v]) != nodes_so_far.end())
            nodes_so_far_expr += x[v];
    }
    model.addConstr(nodes_so_far_expr <= data->max_overlap * size_expr);
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::addTerminalConstraints ()
Definition at line 219 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetData::terminals, and deregnet::DeregnetModel< Model, Data >::x.
                                                        { // consider using complement of terminals ...
    for (NodeIt v(*graph); v != INVALID; ++v) {
        std::set<Node>* terminals { data->terminals };
        if (terminals->find(v) == terminals->end()) {
            GRBLinExpr out_neighbor_expr;
            for (OutArcIt a(*graph, v); a != INVALID; ++a)
                out_neighbor_expr += x[graph->target(a)];
            model.addConstr(x[v] - out_neighbor_expr <= 0);
        }
    }
    model.update();
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::createVariables ()
Definition at line 118 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot(), deregnet::DeregnetModel< Model, Data >::createVariablesRoot(), deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::root.
                                                 {
    if (root)
        createVariablesRoot();
    else
        createVariablesNoRoot();
    model.update();
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot () [private]
Referenced by deregnet::DeregnetModel< Model, Data >::createVariables().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::createVariablesNoRoot () [inline], [private]
Definition at line 290 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::score, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                               {
    y = new std::map<Node, GRBVar>;
    for (NodeIt v(*graph); v != INVALID; ++v) {
        x[v] = model.addVar(0.0, 1.0, (*score)[v], GRB_BINARY);
        (*y)[v] = model.addVar(0.0, 1.0, 0.0, GRB_BINARY);
    }
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::createVariablesNoRoot () [inline], [private]
Definition at line 299 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::score, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                                     {
    y = new std::map<Node, GRBVar>;
    for (NodeIt v(*graph); v != INVALID; ++v) {
        x[v] = model.addVar(0.0, 1.0, (*score)[v], 1.0, GRB_BINARY);
        (*y)[v] = model.addVar(0.0, 1.0, 0.0, 0.0, GRB_BINARY);
    }
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::createVariablesRoot () [private]
Referenced by deregnet::DeregnetModel< Model, Data >::createVariables().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::createVariablesRoot () [inline], [private]
Definition at line 278 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::score, and deregnet::DeregnetModel< Model, Data >::x.
                                                             {
    for (NodeIt v(*graph); v != INVALID; ++v)
        x[v] = model.addVar(0.0, 1.0, (*score)[v], GRB_BINARY);
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::createVariablesRoot () [inline], [private]
Definition at line 284 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::score, and deregnet::DeregnetModel< Model, Data >::x.
                                                                   {
    for (NodeIt v(*graph); v != INVALID; ++v)
        x[v] = model.addVar(0.0, 1.0, (*score)[v], 1.0, GRB_BINARY);
}
template<typename Model , typename Data > Solution deregnet::DeregnetModel< Model, Data >::getCurrentSolution ()
Definition at line 256 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::Solution::avg_score, deregnet::Solution::edgelist, deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::Solution::nodes, deregnet::Solution::rootid, and deregnet::Solution::total_score.
                                                        {
    Solution solution;
    std::set<Node> nodes;
    string rootid;
    _getCurrentSolution(&rootid, &nodes, &solution);
    for (auto v : nodes) {
        std::string source = (*nodeid)[v];
        for (OutArcIt a(*graph, v); a != INVALID; ++a) {
            std::string target { (*nodeid)[graph->target(a)] };
            if (solution.nodes.find(target) != solution.nodes.end())
                solution.edgelist.insert(std::make_pair(source, target));
        }
    }
    solution.rootid = rootid;
    solution.avg_score = solution.total_score / solution.nodes.size();
    return solution;
}
template<typename Model , typename Data > GRBLinExpr deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon () [private]
Definition at line 151 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
Referenced by deregnet::DeregnetModel< Model, Data >::addBaseConstraintsNoRoot().
                                                                      {
    GRBLinExpr subgraph_size_lhs;
    GRBLinExpr exactly_one_root_lhs;
    for (NodeIt v(*graph); v != INVALID; ++v) {
        model.addConstr((*y)[v] <= x[v]);
        subgraph_size_lhs += x[v];
        exactly_one_root_lhs += (*y)[v];
        GRBLinExpr parent_sum;
        for (InArcIt a(*graph,v); a != INVALID; ++a)
            parent_sum += x[graph->source(a)];
        model.addConstr(x[v] - (*y)[v] - parent_sum <= 0);
    }
    model.addConstr(exactly_one_root_lhs == 1);
    return subgraph_size_lhs;
}
template<typename Model , typename Data > GRBLinExpr deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon () [private]
Definition at line 136 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::root, and deregnet::DeregnetModel< Model, Data >::x.
Referenced by deregnet::DeregnetModel< Model, Data >::addBaseConstraintsRoot().
                                                                    {
    GRBLinExpr subgraph_size_lhs;
    for (NodeIt v(*graph); v != INVALID; ++v) {
        subgraph_size_lhs += x[v];
        GRBLinExpr parent_sum;
        for (InArcIt a(*graph,v); a != INVALID; ++a)
            parent_sum += x[graph->source(a)];
        if (v != *root)
            model.addConstr(x[v] - parent_sum <= 0);
    }
    model.addConstr(x[*root] == 1);
    return subgraph_size_lhs;
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot () [private]
Referenced by deregnet::DeregnetModel< Model, Data >::setup_solve().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::setCallbackNoRoot () [inline], [private]
Definition at line 372 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetData::gap_cut, deregnet::DeregnetModel< Model, Data >::graph, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                           {
    model.setCallback(new LazyConstraintCallbackNoRoot(&x, y, graph,
      data->gap_cut));
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::setCallbackNoRoot () [inline], [private]
Definition at line 377 of file DeregnetModel.h.
                                                                 {
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::setCallbackRoot () [private]
Referenced by deregnet::DeregnetModel< Model, Data >::setup_solve().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::setCallbackRoot () [inline], [private]
Definition at line 363 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetData::gap_cut, deregnet::DeregnetModel< Model, Data >::graph, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::root, and deregnet::DeregnetModel< Model, Data >::x.
                                                         {
    model.setCallback(new LazyConstraintCallbackRoot(&x, graph, root,
      data->gap_cut));
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::setCallbackRoot () [inline], [private]
Definition at line 368 of file DeregnetModel.h.
                                                               {
}
template<typename Model, typename Data> void deregnet::DeregnetModel< Model, Data >::setStartSolution (std::pair< Node, std::set< Node >> * start_solution) [private]
Referenced by deregnet::DeregnetModel< Model, Data >::setup_solve().
template<> void deregnet::DeregnetModel< GRBModel, DrgntData >::setStartSolution (std::pair< Node, std::set< Node >> * start_solution) [inline], [private]
Definition at line 330 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::root, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                                                                     {
    for (NodeIt v(*graph); v != INVALID; ++v) {
        if ((start_solution->second).find(v) != (start_solution->second).end())
            x[v].set(GRB_DoubleAttr_Start, 1.0);
        else
            x[v].set(GRB_DoubleAttr_Start, 0.0);
        if (!root) {
            if (v == start_solution->first)
                (*y)[v].set(GRB_DoubleAttr_Start, 1.0);
            else
                (*y)[v].set(GRB_DoubleAttr_Start, 0.0);
        }
    }
}
template<> void deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::setStartSolution (std::pair< Node, std::set< Node >> * start_solution) [inline], [private]
Definition at line 346 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::root, deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                                                                           
      {
    for (NodeIt v(*graph); v != INVALID; ++v) {
        if ((start_solution->second).find(v) != (start_solution->second).end())
            model.setStartSolution(x[v], 1.0);
        else
            model.setStartSolution(x[v], 1.0);
        if (!root) {
            if (v == start_solution->first)
                model.setStartSolution((*y)[v], 1.0);
            else
                model.setStartSolution((*y)[v], 0.0);
        }
    }
}
template<typename Model , typename Data > void deregnet::DeregnetModel< Model, Data >::setup_solve (std::pair< Node, std::set< Node >> * start_solution) [private]
Definition at line 233 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetData::model_sense, deregnet::DeregnetModel< Model, Data >::root, deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot(), deregnet::DeregnetModel< Model, Data >::setCallbackRoot(), deregnet::DeregnetModel< Model, Data >::setStartSolution(), and deregnet::DeregnetData::time_limit.
Referenced by deregnet::DeregnetModel< Model, Data >::solve().
                                                                                        {
    if (data->model_sense == "min")
        model.set(GRB_IntAttr_ModelSense, GRB_MINIMIZE);
    else
        model.set(GRB_IntAttr_ModelSense, GRB_MAXIMIZE);
    model.set(GRB_IntParam_LazyConstraints, 1);
    if (data->time_limit)
        model.set(GRB_DoubleParam_TimeLimit, *(data->time_limit));
    if (start_solution)
        setStartSolution(start_solution);
    if (root)
        setCallbackRoot();
    else
        setCallbackNoRoot();
    model.update();
}
template<typename Model, typename Data> bool deregnet::DeregnetModel< Model, Data >::solve (std::pair< Node, std::set< Node >> * start_solution)
template<> bool deregnet::DeregnetModel< GRBModel, DrgntData >::solve (std::pair< Node, std::set< Node >> * start_solution) [inline]
Definition at line 381 of file DeregnetModel.h.
References deregnet::DeregnetModel< Model, Data >::model, and deregnet::DeregnetModel< Model, Data >::setup_solve().
                                                                                          {
    setup_solve(start_solution);
    model.optimize();
    int status = model.get(GRB_IntAttr_Status); // FMILP implmentation of status!
    return status == GRB_OPTIMAL || status == GRB_INTERRUPTED || status == GRB_TIME_LIMIT;
}
template<> bool deregnet::DeregnetModel< grbfrc::FMILP, AvgdrgntData >::solve (std::pair< Node, std::set< Node >> * start_solution) [inline]
Definition at line 389 of file DeregnetModel.h.
References deregnet::AvgdrgntData::algorithm, deregnet::DeregnetModel< Model, Data >::data, deregnet::DeregnetData::gap_cut, deregnet::DeregnetModel< Model, Data >::graph, INVALID, deregnet::AvgdrgntData::min_size, deregnet::DeregnetModel< Model, Data >::model, deregnet::DeregnetModel< Model, Data >::root, deregnet::DeregnetModel< Model, Data >::score, deregnet::DeregnetModel< Model, Data >::setup_solve(), deregnet::DeregnetModel< Model, Data >::x, and deregnet::DeregnetModel< Model, Data >::y.
                                                                                                {
    setup_solve(start_solution);
    // add callback here
    grbfrc::GrbfrcCallback<Node>* cb;
    if (root) {
        std::vector<std::map<Node, GRBVar>>* vargrps = new std::vector<std::map<Node, GRBVar>>({
      x });
        GrbfrcLazyConstraintCallbackRoot* callback = new GrbfrcLazyConstraintCallbackRoot(
      graph, root, data->gap_cut);
        cb = new grbfrc::GrbfrcCallback<Node>(callback, vargrps);
    }
    else {
        std::vector<std::map<Node, GRBVar>>* vargrps = new std::vector<std::map<Node, GRBVar>>({
      x, *y });
        GrbfrcLazyConstraintCallbackNoRoot* callback = new GrbfrcLazyConstraintCallbackNoRoot(
      graph, data->gap_cut);
        cb = new grbfrc::GrbfrcCallback<Node>(callback, vargrps);
    }
    double objlb = 0.0;
    double objub = 0.0;
    std::set<Node> maxnodes;
    for (int k = 0; k <= data->min_size; ++k) {
        double ub = -1000000.0;
        for (NodeIt v(*graph); v != INVALID; ++v) {
            if (maxnodes.find(v) == maxnodes.end() && score->operator[](v) > ub) {
                ub = score->operator[](v);
                objub += ub;
                maxnodes.insert(v);
            }
        }
    }
    objub = objub / data->min_size;
    std::cout << objub << std::endl;
    model.optimize(data->algorithm, cb, &objub, &objlb);
    int status = model.get(GRB_IntAttr_Status);
    return status == GRB_OPTIMAL || status == GRB_INTERRUPTED || status == GRB_TIME_LIMIT;
}
Member Data Documentation
template<typename Model, typename Data> Data* deregnet::DeregnetModel< Model, Data >::data [protected]
Definition at line 71 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::addBaseConstraintsNoRoot(), deregnet::DeregnetModel< Model, Data >::addBaseConstraintsRoot(), deregnet::DeregnetModel< Model, Data >::addExcludeConstraints(), deregnet::DeregnetModel< Model, Data >::addIncludeConstraints(), deregnet::DeregnetModel< Model, Data >::addReceptorConstraints(), deregnet::DeregnetModel< Model, Data >::addSuboptimalityConstraint(), deregnet::DeregnetModel< Model, Data >::addTerminalConstraints(), deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot(), deregnet::DeregnetModel< Model, Data >::setCallbackRoot(), deregnet::DeregnetModel< Model, Data >::setup_solve(), and deregnet::DeregnetModel< Model, Data >::solve().
template<typename Model, typename Data> GRBEnv deregnet::DeregnetModel< Model, Data >::env [protected]
Definition at line 66 of file DeregnetModel.h.
template<typename Model, typename Data> Graph* deregnet::DeregnetModel< Model, Data >::graph [protected]
Definition at line 72 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::addReceptorConstraints(), deregnet::DeregnetModel< Model, Data >::addSuboptimalityConstraint(), deregnet::DeregnetModel< Model, Data >::addTerminalConstraints(), deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot(), deregnet::DeregnetModel< Model, Data >::createVariablesRoot(), deregnet::DeregnetModel< Model, Data >::DeregnetModel(), deregnet::DeregnetModel< Model, Data >::getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon(), deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot(), deregnet::DeregnetModel< Model, Data >::setCallbackRoot(), deregnet::DeregnetModel< Model, Data >::setStartSolution(), and deregnet::DeregnetModel< Model, Data >::solve().
template<typename Model, typename Data> Model deregnet::DeregnetModel< Model, Data >::model { Model(env) } [protected]
Definition at line 67 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::addBaseConstraints(), deregnet::DeregnetModel< Model, Data >::addBaseConstraintsNoRoot(), deregnet::DeregnetModel< Model, Data >::addBaseConstraintsRoot(), deregnet::DeregnetModel< Model, Data >::addExcludeConstraints(), deregnet::DeregnetModel< Model, Data >::addIncludeConstraints(), deregnet::DeregnetModel< Model, Data >::addReceptorConstraints(), deregnet::DeregnetModel< Model, Data >::addSuboptimalityConstraint(), deregnet::DeregnetModel< Model, Data >::addTerminalConstraints(), deregnet::DeregnetModel< Model, Data >::createVariables(), deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot(), deregnet::DeregnetModel< Model, Data >::createVariablesRoot(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon(), deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot(), deregnet::DeregnetModel< Model, Data >::setCallbackRoot(), deregnet::DeregnetModel< Model, Data >::setStartSolution(), deregnet::DeregnetModel< Model, Data >::setup_solve(), and deregnet::DeregnetModel< Model, Data >::solve().
template<typename Model, typename Data> NodeMap<std::string>* deregnet::DeregnetModel< Model, Data >::nodeid [protected]
Definition at line 74 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::addSuboptimalityConstraint(), and deregnet::DeregnetModel< Model, Data >::DeregnetModel().
template<typename Model, typename Data> Node* deregnet::DeregnetModel< Model, Data >::root [protected]
Definition at line 75 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::addBaseConstraints(), deregnet::DeregnetModel< Model, Data >::addReceptorConstraints(), deregnet::DeregnetModel< Model, Data >::createVariables(), deregnet::DeregnetModel< Model, Data >::DeregnetModel(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon(), deregnet::DeregnetModel< Model, Data >::setCallbackRoot(), deregnet::DeregnetModel< Model, Data >::setStartSolution(), deregnet::DeregnetModel< Model, Data >::setup_solve(), and deregnet::DeregnetModel< Model, Data >::solve().
template<typename Model, typename Data> NodeMap<double>* deregnet::DeregnetModel< Model, Data >::score [protected]
Definition at line 73 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot(), deregnet::DeregnetModel< Model, Data >::createVariablesRoot(), deregnet::DeregnetModel< Model, Data >::DeregnetModel(), and deregnet::DeregnetModel< Model, Data >::solve().
template<typename Model, typename Data> std::map<Node, GRBVar> deregnet::DeregnetModel< Model, Data >::x [protected]
Definition at line 68 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::addExcludeConstraints(), deregnet::DeregnetModel< Model, Data >::addIncludeConstraints(), deregnet::DeregnetModel< Model, Data >::addSuboptimalityConstraint(), deregnet::DeregnetModel< Model, Data >::addTerminalConstraints(), deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot(), deregnet::DeregnetModel< Model, Data >::createVariablesRoot(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsRootCommon(), deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot(), deregnet::DeregnetModel< Model, Data >::setCallbackRoot(), deregnet::DeregnetModel< Model, Data >::setStartSolution(), and deregnet::DeregnetModel< Model, Data >::solve().
template<typename Model, typename Data> std::map<Node, GRBVar>* deregnet::DeregnetModel< Model, Data >::y { nullptr } [protected]
Definition at line 69 of file DeregnetModel.h.
Referenced by deregnet::DeregnetModel< Model, Data >::_getCurrentSolution(), deregnet::DeregnetModel< Model, Data >::addReceptorConstraints(), deregnet::DeregnetModel< Model, Data >::createVariablesNoRoot(), deregnet::DeregnetModel< Model, Data >::setBaseConstraintsNoRootCommon(), deregnet::DeregnetModel< Model, Data >::setCallbackNoRoot(), deregnet::DeregnetModel< Model, Data >::setStartSolution(), and deregnet::DeregnetModel< Model, Data >::solve().
The documentation for this class was generated from the following file:
/home/sebastian/wrk/deregnet/deregnet/include/deregnet/DeregnetModel.h