grbfrc::FMILP Class Reference
#include <FMILP.h>
Public Member Functions
FMILP (GRBEnv &env, GRBLinExpr objNumerator, GRBLinExpr objDenominator, int objSense)
FMILP (GRBEnv &grbEnv)
FMILP (GRBEnv &grbEnv, GRBLinExpr objNumerator, GRBLinExpr objDenominator)
FMILP (GRBEnv &grbEnv, int objSense)
GRBModel baseModelCopy ()
FMILP copy ()
int get (GRB_IntAttr attr)
double get (GRB_DoubleAttr attr)
std::string get (GRB_StringAttr attr)
void set (GRB_IntAttr attr, int val)
void set (GRB_DoubleAttr attr, double val)
void set (GRB_StringAttr attr, std::string val)
void set (GRB_IntParam attr, int val)
void set (GRB_DoubleParam attr, double val)
void set (GRB_StringParam attr, std::string val)
void setEnv (GRB_IntParam para, int val)
GRBVar & addVar (double lowerBound, double upperBound, char type, std::string name=``)
GRBVar & addVar (double lowerBound, double upperBound, double numeratorCoeff, double denominatorCoeff, char type, std::string name=``)
GRBVar * getVars ()
void update ()
void setObjNumerator (GRBLinExpr &objNumerator)
void setObjDenominator (GRBLinExpr &objDenominator)
int getObjSense ()
void setObjSense (int obj_sense)
void addConstr (const GRBLinExpr lhsExpr, char sense, const GRBLinExpr rhsExpr, std::string name=``)
void addConstr (const GRBLinExpr lhsExpr, char sense, GRBVar rhsVar, std::string name=``)
void addConstr (const GRBLinExpr lhsExpr, char sense, double rhsVal, std::string name=``)
void addConstr (GRBVar lhsVar, char sense, GRBVar rhsVar, std::string name=``)
void addConstr (GRBVar lhsVar, char sense, double rhsVal, std::string name=``)
void addConstr (GRBTempConstr tc, std::string name=``)
void addConstr (const GRBLinExpr expr, double lower, double upper)
GRBConstr * getConstrs ()
GRBLinExpr getRow (GRBConstr &constr)
bool isFLP ()
bool checkUnisignance (std::string sign)
bool isUnisignant ()
void optimize (Algorithm algorithm=Algorithm::GCC)
double getObjVal ()
double getVal (GRBVar &var)
void runCharnesCooper (int time_limit=1200)
void runCharnesCooper (GRBCallback &callback, int time_limit=1200)
GRBModel getCharnesCooperTransform ()
void runDinkelbach (double qi=0.0, int max_iter=10, int time_limit=1200, double tol=0.01, bool verbose=true, bool logFile=true, std::string logFileName=`grbfrc.log`)
void runDinkelbach (GRBCallback &callback, double qi=0.0, int max_iter=10, int time_limit=1200, double tol=0.01, bool verbose=true, bool logFile=true, std::string logFileName=`grbfrc.log`)
void runGeneralizedCharnesCooper (int time_limit=1200)
void runYGGY (GRBCallback callback, int time_limit=1200)
GRBModel getYGGYTransform ()
void printSolution ()
Private Attributes
GRBModel * baseModel
FMILPObj objective
FMILPSol * solution = nullptr
std::vector< GRBVar * > vars
Friends
class CharnesCooper
class Dinkelbach
class YGGY
class Gloverizer
Detailed Description
Definition at line 80 of file FMILP.h.
Constructor & Destructor Documentation
grbfrc::FMILP::FMILP (GRBEnv & env, GRBLinExpr objNumerator, GRBLinExpr objDenominator, int objSense)
Definition at line 14 of file FMILP.cpp.
References baseModel, grbfrc::FMILPObj::denominator, grbfrc::maybe, grbfrc::FMILPObj::numerator, objective, grbfrc::FMILPObj::sense, solution, and grbfrc::FMILPObj::uniSign.
             : baseModel { new GRBModel(env) }
 {
  objective.numerator = objNumerator;
  objective.denominator = objDenominator;
  baseModel->setObjective(objDenominator);
  objective.sense = objSense;
  objective.uniSign = UniSignStatus::maybe;
  solution = nullptr;
 }
grbfrc::FMILP::FMILP (GRBEnv & grbEnv)
Definition at line 29 of file FMILP.cpp.
References objective, grbfrc::FMILPObj::uniSign, and grbfrc::yes.
       : FMILP(grbEnv, 0.0, 0.0, GRB_MAXIMIZE)
 { objective.uniSign = UniSignStatus::yes; }
grbfrc::FMILP::FMILP (GRBEnv & grbEnv, GRBLinExpr objNumerator, GRBLinExpr objDenominator)
Definition at line 33 of file FMILP.cpp.
       : FMILP(grbEnv, objNumerator, objDenominator, GRB_MAXIMIZE)
 { }
grbfrc::FMILP::FMILP (GRBEnv & grbEnv, int objSense)
Definition at line 39 of file FMILP.cpp.
References objective, grbfrc::FMILPObj::uniSign, and grbfrc::yes.
       : FMILP(grbEnv, 0.0, 0.0, objSense)
 { objective.uniSign = UniSignStatus::yes; }
Member Function Documentation
void grbfrc::FMILP::addConstr (const GRBLinExpr lhsExpr, char sense, const GRBLinExpr rhsExpr, std::string name = ``)
Definition at line 121 of file FMILP.cpp.
References baseModel.
Referenced by main().
 { baseModel->addConstr(lhsExpr, sense, rhsExpr, name); }
void grbfrc::FMILP::addConstr (const GRBLinExpr lhsExpr, char sense, GRBVar rhsVar, std::string name = ``)
Definition at line 127 of file FMILP.cpp.
References baseModel.
 { baseModel->addConstr(lhsExpr, sense, rhsVar, name); }
void grbfrc::FMILP::addConstr (const GRBLinExpr lhsExpr, char sense, double rhsVal, std::string name = ``)
Definition at line 133 of file FMILP.cpp.
References baseModel.
 { baseModel->addConstr(lhsExpr, sense, rhsVal, name); }
void grbfrc::FMILP::addConstr (GRBVar lhsVar, char sense, GRBVar rhsVar, std::string name = ``)
Definition at line 139 of file FMILP.cpp.
References baseModel.
 { baseModel->addConstr(lhsVar, sense, rhsVar, name); }
void grbfrc::FMILP::addConstr (GRBVar lhsVar, char sense, double rhsVal, std::string name = ``)
Definition at line 145 of file FMILP.cpp.
References baseModel.
 { baseModel->addConstr(lhsVar, sense, rhsVal, name); }
void grbfrc::FMILP::addConstr (GRBTempConstr tc, std::string name = ``)
Definition at line 151 of file FMILP.cpp.
References baseModel.
 { baseModel->addConstr(tc, name); }
void grbfrc::FMILP::addConstr (const GRBLinExpr expr, double lower, double upper)
Definition at line 155 of file FMILP.cpp.
References baseModel.
 {
  baseModel->addConstr(expr, GRB_GREATER_EQUAL, lower);
  baseModel->addConstr(expr, GRB_LESS_EQUAL, upper);
 }
GRBVar & grbfrc::FMILP::addVar (double lowerBound, double upperBound, char type, std::string name = ``)
Definition at line 81 of file FMILP.cpp.
References baseModel, and vars.
Referenced by main().
 {
  vars.push_back(new GRBVar(baseModel->addVar(lowerBound, upperBound, 0.0, type, name)));
  return *(vars.back());
 }
GRBVar & grbfrc::FMILP::addVar (double lowerBound, double upperBound, double numeratorCoeff, double denominatorCoeff, char type, std::string name = ``)
Definition at line 90 of file FMILP.cpp.
References baseModel, grbfrc::FMILPObj::denominator, grbfrc::FMILPObj::numerator, objective, and vars.
 {
  vars.push_back(new GRBVar(baseModel->addVar(lowerBound, upperBound, denominatorCoeff, type,
      name)));
  objective.numerator += numeratorCoeff * (*(vars.back()));
  objective.denominator += denominatorCoeff * (*(vars.back()));
  return *(vars.back());
 }
GRBModel grbfrc::FMILP::baseModelCopy ()
Definition at line 45 of file FMILP.cpp.
References baseModel.
 { return *baseModel; }
bool grbfrc::FMILP::checkUnisignance (std::string sign)
test
Definition at line 175 of file FMILP.cpp.
References baseModel, grbfrc::FMILPObj::denominator, objective, grbfrc::FMILPObj::uniSign, and grbfrc::yes.
Referenced by isUnisignant().
 {
  if (sign == "positive")
     baseModel->setObjective(objective.denominator, GRB_MINIMIZE);
  else if (sign == "negative")
     baseModel->setObjective(objective.denominator, GRB_MAXIMIZE);
  baseModel->optimize();
  if (sign == "positive" && baseModel->get(GRB_IntAttr_Status) == GRB_OPTIMAL)
   {
    if (baseModel->get(GRB_DoubleAttr_ObjVal) > 0)
     {
      objective.uniSign = UniSignStatus::yes;
      return true;
     }
    else return false ;
   }
  else return false;
  if (sign == "negative" && baseModel->get(GRB_IntAttr_Status) == GRB_OPTIMAL)
   {
    if (baseModel->get(GRB_DoubleAttr_ObjVal) < 0)
     {
      objective.uniSign = UniSignStatus::yes;
      return true;
     }
    else return false;
   }
  else return false;
 }
FMILP grbfrc::FMILP::copy ()
Definition at line 48 of file FMILP.cpp.
 { return *this; }
int grbfrc::FMILP::get (GRB_IntAttr attr)
Definition at line 51 of file FMILP.cpp.
References baseModel.
Referenced by grbfrc::CharnesCooper::backTransformSolution(), grbfrc::YGGY::backTransformSolution(), grbfrc::YGGY::define_constraints(), grbfrc::CharnesCooper::getIndex(), grbfrc::YGGY::getIndex(), grbfrc::YGGY::getUmax(), and grbfrc::CharnesCooper::transform().
 { return baseModel->get(attr); }
double grbfrc::FMILP::get (GRB_DoubleAttr attr)
Definition at line 54 of file FMILP.cpp.
References baseModel.
 { return baseModel->get(attr); }
std::string grbfrc::FMILP::get (GRB_StringAttr attr)
Definition at line 57 of file FMILP.cpp.
References baseModel.
 { return baseModel->get(attr); }
GRBModel grbfrc::FMILP::getCharnesCooperTransform ()
Definition at line 275 of file FMILP.cpp.
References grbfrc::CharnesCooper::getTransform().
 {
  CharnesCooper chaco(*this);
  return chaco.getTransform();
 }
GRBConstr * grbfrc::FMILP::getConstrs ()
Definition at line 163 of file FMILP.cpp.
References baseModel.
Referenced by grbfrc::YGGY::define_constraints(), and grbfrc::CharnesCooper::transform().
 { return baseModel->getConstrs(); }
int grbfrc::FMILP::getObjSense ()
Definition at line 115 of file FMILP.cpp.
References objective, and grbfrc::FMILPObj::sense.
 { return objective.sense; }
double grbfrc::FMILP::getObjVal ()
Definition at line 245 of file FMILP.cpp.
References grbfrc::FMILPSol::objVal, and solution.
                        {
    return solution->objVal;
}
GRBLinExpr grbfrc::FMILP::getRow (GRBConstr & constr)
Definition at line 166 of file FMILP.cpp.
References baseModel.
Referenced by grbfrc::YGGY::define_constraints(), and grbfrc::CharnesCooper::transform().
 { return baseModel->getRow(constr); }
double grbfrc::FMILP::getVal (GRBVar & var)
Definition at line 249 of file FMILP.cpp.
References solution, vars, and grbfrc::FMILPSol::varVals.
                                {
    int index { 0 };
    for (GRBVar* varp : vars) {
        if (varp->sameAs(var))
            return (solution->varVals)[index];
        index++;
    }
}
GRBVar * grbfrc::FMILP::getVars ()
Definition at line 103 of file FMILP.cpp.
References baseModel.
Referenced by main().
 { return baseModel->getVars(); }
GRBModel grbfrc::FMILP::getYGGYTransform ()
Definition at line 321 of file FMILP.cpp.
References baseModel.
 {
  GRBModel model(baseModel->getEnv());
  return model;
 }
bool grbfrc::FMILP::isFLP ()
Definition at line 169 of file FMILP.cpp.
References baseModel.
Referenced by grbfrc::CharnesCooper::CharnesCooper().
 {
  if (baseModel->get(GRB_IntAttr_NumIntVars) == 0) return true;
  else return false;
 }
bool grbfrc::FMILP::isUnisignant ()
test
Definition at line 210 of file FMILP.cpp.
References checkUnisignance(), grbfrc::no, objective, grbfrc::FMILPObj::uniSign, and grbfrc::yes.
 {
  if (checkUnisignance("positive"))
   {
    objective.uniSign = UniSignStatus::yes;
    return true;
   }
  else if (checkUnisignance("negative"))
   {
    objective.uniSign = UniSignStatus::yes;
    return true;
   }
  else
   {
    objective.uniSign = UniSignStatus::no;
    return false;
   }
 }
void grbfrc::FMILP::optimize (Algorithm algorithm = Algorithm::GCC)
Definition at line 234 of file FMILP.cpp.
References grbfrc::CCT, grbfrc::DTA, grbfrc::GCC, runCharnesCooper(), runDinkelbach(), and runGeneralizedCharnesCooper().
                                        {
    if (algorithm == Algorithm::GCC)
        this->runGeneralizedCharnesCooper();
    else if (algorithm == Algorithm::CCT)
        this->runCharnesCooper();
    else if (algorithm == Algorithm::DTA)
        this->runDinkelbach();
    //else if (algorithm == Algorithm::OVT)
        //this->runObjVarTransform();
}
void grbfrc::FMILP::printSolution ()
Definition at line 327 of file FMILP.cpp.
References baseModel, grbfrc::FMILPSol::objVal, solution, vars, and grbfrc::FMILPSol::varVals.
Referenced by main().
 {
  if (solution)
   {
    std::cout << "\n########################### Solution ############################\n\n";
    for (int i = 0; i < baseModel->get(GRB_IntAttr_NumVars); i++)
     {
      double varval { solution->varVals[i] };
      if (varval == 0.0) varval = std::abs(varval);
      std::cout << vars[i]->get(GRB_StringAttr_VarName)
                << ": " << varval << std::endl;
     }
    std::cout << std::endl;
    std::cout << "ObjVal: " << solution->objVal << std::endl;
    std::cout << "\n#################################################################\n\n";
   }
  else
    std::cout << "There is no solution to print!" << std::endl;
 }
void grbfrc::FMILP::runCharnesCooper (int time_limit = 1200)
Definition at line 258 of file FMILP.cpp.
References baseModel, grbfrc::CharnesCooper::run(), and grbfrc::CharnesCooper::writeSolution().
Referenced by main(), and optimize().
 {
  baseModel->update();
  CharnesCooper chaco(*this);
  chaco.run(time_limit);
  chaco.writeSolution();
 }
void grbfrc::FMILP::runCharnesCooper (GRBCallback & callback, int time_limit = 1200)
Definition at line 266 of file FMILP.cpp.
References baseModel, grbfrc::CharnesCooper::run(), and grbfrc::CharnesCooper::writeSolution().
 {
  baseModel->update();
  CharnesCooper chaco(*this);
  chaco.run(callback, time_limit);
  chaco.writeSolution();
 }
void grbfrc::FMILP::runDinkelbach (double qi = 0.0, int max_iter = 10, int time_limit = 1200, double tol = 0.01, bool verbose = true, bool logFile = true, std::string logFileName = `grbfrc.log`)
Definition at line 281 of file FMILP.cpp.
References baseModel, grbfrc::Dinkelbach::run(), and grbfrc::Dinkelbach::writeSolution().
Referenced by main(), and optimize().
 {
  baseModel->update();
  Dinkelbach dinkel(*this, qi, max_iter, time_limit, tol);
  dinkel.run(verbose, logFile, logFileName);
  dinkel.writeSolution();
 }
void grbfrc::FMILP::runDinkelbach (GRBCallback & callback, double qi = 0.0, int max_iter = 10, int time_limit = 1200, double tol = 0.01, bool verbose = true, bool logFile = true, std::string logFileName = `grbfrc.log`)
Definition at line 295 of file FMILP.cpp.
References baseModel, grbfrc::Dinkelbach::run(), and grbfrc::Dinkelbach::writeSolution().
 {
  baseModel->update();
  Dinkelbach dinkel(*this, qi, max_iter, time_limit, tol);
  dinkel.run(callback, verbose, logFile, logFileName);
  dinkel.writeSolution();
 }
void grbfrc::FMILP::runGeneralizedCharnesCooper (int time_limit = 1200)
Definition at line 310 of file FMILP.cpp.
References baseModel, grbfrc::YGGY::run(), and grbfrc::YGGY::writeSolution().
Referenced by optimize().
                                                      {
    baseModel->update();
    YGGY yggy(this);
    yggy.run(time_limit);
    yggy.writeSolution();
}
void grbfrc::FMILP::runYGGY (GRBCallback callback, int time_limit = 1200)
Definition at line 317 of file FMILP.cpp.
Referenced by main().
 { }
void grbfrc::FMILP::set (GRB_IntAttr attr, int val)
Definition at line 60 of file FMILP.cpp.
References baseModel.
 { baseModel->set(attr, val); }
void grbfrc::FMILP::set (GRB_DoubleAttr attr, double val)
Definition at line 63 of file FMILP.cpp.
References baseModel.
 { baseModel->set(attr, val); }
void grbfrc::FMILP::set (GRB_StringAttr attr, std::string val)
Definition at line 66 of file FMILP.cpp.
References baseModel.
 { baseModel->set(attr, val); }
void grbfrc::FMILP::set (GRB_IntParam attr, int val)
Definition at line 69 of file FMILP.cpp.
References baseModel.
 { baseModel->set(param, val); }
void grbfrc::FMILP::set (GRB_DoubleParam attr, double val)
Definition at line 72 of file FMILP.cpp.
References baseModel.
 { baseModel->set(param, val); }
void grbfrc::FMILP::set (GRB_StringParam attr, std::string val)
Definition at line 75 of file FMILP.cpp.
References baseModel.
 { baseModel->set(param, val); }
void grbfrc::FMILP::setEnv (GRB_IntParam para, int val)
Definition at line 78 of file FMILP.cpp.
References baseModel.
 { (baseModel->getEnv()).set(para, val); }
void grbfrc::FMILP::setObjDenominator (GRBLinExpr & objDenominator)
Definition at line 112 of file FMILP.cpp.
References grbfrc::FMILPObj::denominator, and objective.
Referenced by main().
 { objective.denominator = objDenominator; }
void grbfrc::FMILP::setObjNumerator (GRBLinExpr & objNumerator)
Definition at line 109 of file FMILP.cpp.
References grbfrc::FMILPObj::numerator, and objective.
Referenced by main().
 { objective.numerator = objNumerator; }
void grbfrc::FMILP::setObjSense (int obj_sense)
Definition at line 118 of file FMILP.cpp.
References objective, and grbfrc::FMILPObj::sense.
Referenced by main().
 { objective.sense = objSense; }
void grbfrc::FMILP::update ()
Definition at line 106 of file FMILP.cpp.
References baseModel.
Referenced by grbfrc::CharnesCooper::CharnesCooper(), main(), and grbfrc::YGGY::YGGY().
 { baseModel->update(); }
Friends And Related Function Documentation
friend class CharnesCooper [friend]
Definition at line 83 of file FMILP.h.
friend class Dinkelbach [friend]
Definition at line 84 of file FMILP.h.
friend class Gloverizer [friend]
Definition at line 86 of file FMILP.h.
friend class YGGY [friend]
Definition at line 85 of file FMILP.h.
Member Data Documentation
GRBModel* grbfrc::FMILP::baseModel [private]
Definition at line 90 of file FMILP.h.
Referenced by addConstr(), addVar(), baseModelCopy(), grbfrc::CharnesCooper::CharnesCooper(), checkUnisignance(), FMILP(), get(), getConstrs(), getRow(), grbfrc::YGGY::getUmax(), getVars(), getYGGYTransform(), isFLP(), printSolution(), grbfrc::Dinkelbach::run(), runCharnesCooper(), runDinkelbach(), runGeneralizedCharnesCooper(), set(), setEnv(), and update().
FMILPObj grbfrc::FMILP::objective [private]
Definition at line 91 of file FMILP.h.
Referenced by addVar(), checkUnisignance(), FMILP(), getObjSense(), grbfrc::YGGY::getUmax(), isUnisignant(), grbfrc::Dinkelbach::run(), setObjDenominator(), setObjNumerator(), setObjSense(), grbfrc::CharnesCooper::transform(), and grbfrc::YGGY::transform().
FMILPSol* grbfrc::FMILP::solution = nullptr [private]
Definition at line 92 of file FMILP.h.
Referenced by FMILP(), getObjVal(), getVal(), printSolution(), grbfrc::CharnesCooper::writeSolution(), grbfrc::Dinkelbach::writeSolution(), and grbfrc::YGGY::writeSolution().
std::vector<GRBVar*> grbfrc::FMILP::vars [private]
Definition at line 93 of file FMILP.h.
Referenced by addVar(), grbfrc::YGGY::define_tx(), grbfrc::CharnesCooper::getIndex(), grbfrc::YGGY::getIndex(), getVal(), printSolution(), grbfrc::Dinkelbach::run(), and grbfrc::CharnesCooper::transform().
The documentation for this class was generated from the following files:
/home/sebastian/wrk/deregnet/deregnet/grbfrc/include/grbfrc/FMILP.h
/home/sebastian/wrk/deregnet/deregnet/grbfrc/src/FMILP.cpp