deregnet::SuboptimalStartHeuristic Class Reference
#include <SuboptimalStartHeuristic.h>
Public Member Functions
SuboptimalStartHeuristic (Graph *xgraph, NodeMap< double > *xscore, Node *root, std::set< Node > *exclude, std::set< Node > *receptors, std::function< bool(double, double)> xcmp, NodeMap< std::string > *xnodeid, std::set< std::string > *xnodes_sof_far, double xmax_overlap, int xsize)
Private Member Functions
bool is_overlap_node (Node *node)
virtual Node * get_best_root () override
virtual bool search_further () override
virtual bool feasible_node (Node *node) override
Private Attributes
NodeMap< std::string > * nodeid
std::set< std::string > * nodes_so_far
double max_overlap
int size
int current_overlapping_nodes { 0 }
Additional Inherited Members
Detailed Description
Definition at line 47 of file SuboptimalStartHeuristic.h.
Constructor & Destructor Documentation
[SuboptimalStartHeuristic(Graph *xgraph, NodeMap< double > *xscore, Node *root, std::set< Node > *exclude, std::set< Node > *receptors, std::function< bool(double, double)> xcmp, NodeMap< std::string > *xnodeid, std::set< std::string > *xnodes_sof_far, double xmax_overlap, int xsize)]deregnet::SuboptimalStartHeuristic::SuboptimalStartHeuristic (Graph * xgraph, NodeMap< double > * xscore, Node * root, std::set< Node > * exclude, std::set< Node > * receptors, std::function< bool(double, double)> xcmp, NodeMap< std::string > * xnodeid, std::set< std::string > * xnodes_sof_far, double xmax_overlap, int xsize)
Definition at line 44 of file SuboptimalStartHeuristic.cpp.
References max_overlap, nodes_so_far, and size.
 : DeregnetStartHeuristic(xgraph, xscore, root,
      exclude, receptors, xcmp),
   nodeid { xnodeid },
   nodes_so_far { xnodes_sof_far },
   max_overlap { xmax_overlap },
   size { xsize }
{ }
Member Function Documentation
bool deregnet::SuboptimalStartHeuristic::feasible_node (Node * node) [override], [private], [virtual]
Implements deregnet::DeregnetStartHeuristic.
Definition at line 96 of file SuboptimalStartHeuristic.cpp.
References current_overlapping_nodes, is_overlap_node(), max_overlap, and deregnet::DeregnetStartHeuristic::start_solution.
                                                       {
    bool overlap_node { is_overlap_node(node) };
    double potential_overlap { static_cast<double>(current_overlapping_nodes /
      start_solution->size()) };
    if (exclude) {
        if (overlap_node) {
            if (start_solution->find(*node) == start_solution->end()
                && potential_overlap < max_overlap
                && exclude->find(*node) == exclude->end()) {
                current_overlapping_nodes++;
                return true;
            }
        }
        else {
            if (start_solution->find(*node) == start_solution->end() &&
      exclude->find(*node) == exclude->end())
                return true;
        }
    }
    else {
        if (overlap_node) {
            if (start_solution->find(*node) == start_solution->end()
                && potential_overlap < max_overlap) {
                current_overlapping_nodes++;
                return true;
            }
        }
        else {
            if (start_solution->find(*node) == start_solution->end())
                return true;
        }
    }
    return false;
}
Node * deregnet::SuboptimalStartHeuristic::get_best_root () [override], [private], [virtual]
Implements deregnet::DeregnetStartHeuristic.
Definition at line 61 of file SuboptimalStartHeuristic.cpp.
References deregnet::DeregnetStartHeuristic::graph, INVALID, is_overlap_node(), max_overlap, nodes_so_far, and deregnet::DeregnetStartHeuristic::update_best_node().
                                              {
    double best;
    Node* best_node { nullptr };
    bool overlap_matters { max_overlap < 1.0 / nodes_so_far->size() };
    if (receptors)
        for (auto v : *receptors) {
            if (is_overlap_node(&v) && overlap_matters)
                continue;
            else
                update_best_node(&best_node, &v, &best);
        }
    else
        for (NodeIt v(*graph); v != INVALID; ++v) {
            if (is_overlap_node(&v) && overlap_matters)
                continue;
            else
                update_best_node(&best_node, &v, &best);
        }
    return best_node;
}
bool deregnet::SuboptimalStartHeuristic::is_overlap_node (Node * node) [private]
Definition at line 129 of file SuboptimalStartHeuristic.cpp.
References nodeid, and nodes_so_far.
Referenced by feasible_node(), and get_best_root().
                                                         {
    for (set<string>::iterator nodeID = nodes_so_far->begin(); nodeID !=
      nodes_so_far->end(); ++nodeID)
        if (*nodeID == (*nodeid)[*node])
            return true;
    return false;
}
bool deregnet::SuboptimalStartHeuristic::search_further () [override], [private], [virtual]
Implements deregnet::DeregnetStartHeuristic.
Definition at line 82 of file SuboptimalStartHeuristic.cpp.
References deregnet::DeregnetStartHeuristic::found_node, size, and deregnet::DeregnetStartHeuristic::success.
                                              {
    size--;
    if (size > 0 && found_node)
        return true;
    else if (size > 0 && !found_node)
        return false;
    else if (size == 0) {
        success = true;
        return false;
    }
    else
        return false;
}
Member Data Documentation
int deregnet::SuboptimalStartHeuristic::current_overlapping_nodes { 0 } [private]
Definition at line 55 of file SuboptimalStartHeuristic.h.
Referenced by feasible_node().
double deregnet::SuboptimalStartHeuristic::max_overlap [private]
Definition at line 53 of file SuboptimalStartHeuristic.h.
Referenced by feasible_node(), get_best_root(), and SuboptimalStartHeuristic().
NodeMap<std::string>* deregnet::SuboptimalStartHeuristic::nodeid [private]
Definition at line 51 of file SuboptimalStartHeuristic.h.
Referenced by is_overlap_node().
std::set<std::string>* deregnet::SuboptimalStartHeuristic::nodes_so_far [private]
Definition at line 52 of file SuboptimalStartHeuristic.h.
Referenced by get_best_root(), is_overlap_node(), and SuboptimalStartHeuristic().
int deregnet::SuboptimalStartHeuristic::size [private]
Definition at line 54 of file SuboptimalStartHeuristic.h.
Referenced by search_further(), and SuboptimalStartHeuristic().
The documentation for this class was generated from the following files:
/home/sebastian/wrk/deregnet/deregnet/include/deregnet/SuboptimalStartHeuristic.h
/home/sebastian/wrk/deregnet/deregnet/src/SuboptimalStartHeuristic.cpp