/home/sebastian/wrk/deregnet/deregnet/grbfrc/examples/example2.cpp File Reference
#include <gurobi_c++.h>
*
#include <grbfrc.h>
*
Typedefs
using FMILP = grbfrc::FMILP
Functions
int main ()
Typedef Documentation
using FMILP = grbfrc::FMILP
Definition at line 4 of file example2.cpp.
Function Documentation
int main (void)
Definition at line 6 of file example2.cpp.
References grbfrc::FMILP::addConstr(), grbfrc::FMILP::addVar(), grbfrc::FMILP::printSolution(), grbfrc::FMILP::runCharnesCooper(), grbfrc::FMILP::setObjDenominator(), grbfrc::FMILP::setObjNumerator(), grbfrc::FMILP::setObjSense(), and grbfrc::FMILP::update().
 {
  GRBEnv env;
  FMILP model(env);
  GRBVar x = model.addVar(0.0, GRB_INFINITY, GRB_CONTINUOUS, "x");
  GRBVar y = model.addVar(0.0, 6.0, GRB_CONTINUOUS, "y");
  model.update();
  model.addConstr(-x + y <= 4.0);
  model.addConstr(2*x + y <= 14.0);
  GRBLinExpr objNum { -2*x + y + 2};
  model.setObjNumerator(objNum);
  GRBLinExpr objDenom { x + 3*y + 4 };
  model.setObjDenominator(objDenom);
  model.setObjSense(GRB_MINIMIZE);
  model.runCharnesCooper();
  model.printSolution();
 }