/home/sebastian/wrk/deregnet/deregnet/grbfrc/examples/example10.cpp File Reference
#include <gurobi_c++.h>
*
#include <grbfrc.h>
*
Typedefs
using FMILP = grbfrc::FMILP
Functions
int main (void)
Typedef Documentation
using FMILP = grbfrc::FMILP
Definition at line 4 of file example10.cpp.
Function Documentation
int main (void)
Definition at line 6 of file example10.cpp.
References grbfrc::FMILP::addConstr(), grbfrc::FMILP::addVar(), grbfrc::FMILP::printSolution(), grbfrc::FMILP::runYGGY(), grbfrc::FMILP::setObjDenominator(), grbfrc::FMILP::setObjNumerator(), grbfrc::FMILP::setObjSense(), and grbfrc::FMILP::update().
 {
  GRBEnv env;
  FMILP model(env);
  GRBVar x = model.addVar(0.0, GRB_INFINITY, GRB_CONTINUOUS, "x");
  GRBVar y = model.addVar(0.0, 6.0, GRB_CONTINUOUS, "y");
  model.update();
  model.addConstr(-x + y <= 4.0);
  model.addConstr(2*x + y <= 14.0);
  GRBVar u = model.addVar(0.0, 1.0, GRB_BINARY, "u");
  GRBVar v = model.addVar(0.0, 1.0, GRB_BINARY, "v");
  model.update();
  model.addConstr(u + v <= 1);
  GRBLinExpr objNum { x + u + 2 };
  model.setObjNumerator(objNum);
  GRBLinExpr objDenom { y + v + 4 };
  model.setObjDenominator(objDenom);
  model.setObjSense(GRB_MINIMIZE);
  model.runYGGY();
  model.printSolution();
  return 0;
 }