/home/sebastian/wrk/deregnet/deregnet/grbfrc/examples/example7.cpp File Reference
#include <gurobi_c++.h>
*
#include <grbfrc.h>
*
#include <cmath>
*
#include <fstream>
*
Classes
class myCallback
Typedefs
using FMILP = grbfrc::FMILP
Functions
int main ()
Typedef Documentation
using FMILP = grbfrc::FMILP
Definition at line 7 of file example7.cpp.
Function Documentation
int main (void)
Definition at line 125 of file example7.cpp.
References grbfrc::FMILP::addConstr(), grbfrc::FMILP::addVar(), grbfrc::FMILP::getVars(), myCallback::logfile, grbfrc::FMILP::printSolution(), grbfrc::FMILP::runDinkelbach(), grbfrc::FMILP::setObjDenominator(), grbfrc::FMILP::setObjNumerator(), grbfrc::FMILP::setObjSense(), grbfrc::FMILP::update(), and myCallback::vars.
 {
  // define model as usual
  GRBEnv env;
  FMILP model(env);
  GRBVar x = model.addVar(0.0, GRB_INFINITY, GRB_CONTINUOUS, "x");
  GRBVar y = model.addVar(0.0, GRB_INFINITY, GRB_CONTINUOUS, "y");
  GRBVar z = model.addVar(0.0, GRB_INFINITY, GRB_CONTINUOUS, "z");
  GRBVar u = model.addVar(0.0, 1.0, GRB_BINARY, "u");
  GRBVar v = model.addVar(0.0, 1.0, GRB_BINARY, "v");
  model.update();
  model.addConstr(x + 3*y + z <= 10);
  model.addConstr(3*x + 2*y <= 7);
  model.addConstr(u + v >= 1);
  GRBLinExpr objNum { 2*x + y + 3*z + u + v + 6 };
  model.setObjNumerator(objNum);
  GRBLinExpr objDenom { x + 3*z + v + 4 };
  model.setObjDenominator(objDenom);
  model.setObjSense(GRB_MAXIMIZE);
  // define callback
  GRBVar* vars = model.getVars();
  std::ofstream logfile("cb.log");
  myCallback cb { 5, vars, &logfile };
  // run Dinkelbach's algorithm with callback
  model.runDinkelbach(cb);
  model.printSolution();
 }