deregnet Namespace Reference
Classes
class AvgdrgntData
Represents all data and parameters to run the average version of the DeRegNet.
class AvgStartHeuristic
Implementation of the heuristic solution algorithm for average DeRegNet algorithm.
class AvgSuboptimalStartHeuristic
Implementation of the heuristic solution algorithm for the suboptimal part of the average DeRegNet algorithm.
class DeregnetData
Represents all shared parameters and data needed to run a DeRegNet algorithm.
class DeregnetFinder
Main entry point for running DeRegNet algorithms.
class DeregnetModel
Implements the mathematical optimization problems which are the basis of the DeRegNet algorithms.
class DeregnetStartHeuristic
Abstract base class for greedy start heuristics.
class DrgntData
Represents all data and parameters needed to run the absolute version of DeRegNet.
class GrbfrcLazyConstraintCallbackNoRoot
Wrapper for lazy constraint callback needed for fractional integer formulation (no fixed root)
class GrbfrcLazyConstraintCallbackRoot
Wrapper for lazy constraint callback needed for fractional integer formulation (fixed root)
class LazyConstraintCallback
Base lazy constraint callback class.
class LazyConstraintCallbackNoRoot
Implementation of the callback when there is no fixed root.
class LazyConstraintCallbackRoot
Implementation of the callback when there is a fixed root.
struct Solution
Representation of a solution to one of the DeRegNet problems.
class StartHeuristic
Implementation of heuristic start solution algorithm for absolute optimal DeRegNet algorithm.
struct Subgraph
Representation of a subgraph corresponding to a Solution.
class SuboptimalStartHeuristic
Implementation of the heuristic solution algorithm for suboptimal part of the absolute DeRegNet algorithm.
Typedefs
using Algorithm = grbfrc::Algorithm
One of the grbfrc algorithms to solve Fractional integer problems.
using FMILP = grbfrc::FMILP
using Graph = lemon::SmartDigraph
using Node = Graph::Node
using NodeIt = Graph::NodeIt
using OutArcIt = Graph::OutArcIt
using InArcIt = Graph::InArcIt
template<typename ValueType >
using NodeMap = Graph::NodeMap< ValueType >
using NodeFilter = NodeMap< bool >
using InducedSubgraph = lemon::FilterNodes< Graph >
Functions
set< string > split_string (const string &str, const string &sep)
void register_node_set (set< string > **node_set, string comma_separated_list_of_nodes)
void register_node_set_file (set< string > **node_set, string path2file)
bool getNodeById (Graph *graph, NodeMap< std::string > *nodeid, std::string id, Node *node)
void write2sif (Graph *graph, std::set< Node > &node_set, NodeMap< std::string > *nodeid, std::string path2file)
std::set< std::string > split_string (const std::string &str, const std::string &sep)
Split a string into token based on some seperation token.
template<typename T >
void set_union (std::set< T > **A, const std::set< T > &B)
Inplace set union.
void register_node_set (std::set< std::string > **node_set, std::string comma_separated_list_of_nodes)
Parse a comma-seperated list of token into a set containing the tokens.
void register_node_set_file (std::set< std::string > **node_set, std::string path2file)
Parse contents of token file into a set containing the tokens.
Typedef Documentation
Algorithm
using deregnet::Algorithm = typedef grbfrc::Algorithm
One of the grbfrc algorithms to solve Fractional integer problems.
Definition at line 46 of file AvgdrgntData.hpp.
FMILP
using deregnet::FMILP = typedef grbfrc::FMILP
Definition at line 58 of file DeregnetFinder.hpp.
Graph
using deregnet::Graph = typedef lemon::SmartDigraph
Definition at line 47 of file usinglemon.hpp.
InArcIt
using deregnet::InArcIt = typedef Graph::InArcIt
Definition at line 54 of file usinglemon.hpp.
InducedSubgraph
using deregnet::InducedSubgraph = typedef lemon::FilterNodes<Graph>
Definition at line 61 of file usinglemon.hpp.
Node
using deregnet::Node = typedef Graph::Node
Definition at line 49 of file usinglemon.hpp.
NodeFilter
using deregnet::NodeFilter = typedef NodeMap<bool>
Definition at line 59 of file usinglemon.hpp.
NodeIt
using deregnet::NodeIt = typedef Graph::NodeIt
Definition at line 51 of file usinglemon.hpp.
NodeMap
template<typename ValueType >
using deregnet::NodeMap = typedef Graph::NodeMap<ValueType>
Definition at line 57 of file usinglemon.hpp.
OutArcIt
using deregnet::OutArcIt = typedef Graph::OutArcIt
Definition at line 53 of file usinglemon.hpp.
Function Documentation
getNodeById()
bool deregnet::getNodeById (Graph * graph, NodeMap< std::string > * nodeid, std::string id, Node * node)
Parameters
graph
nodeid
id
node
Returns
Definition at line 124 of file utils.cpp.
References INVALID.
Referenced by deregnet::DeregnetData::get_node_set(), deregnet::DeregnetData::get_root(), and deregnet::DeregnetFinder< ModelType, Data >::to_subgraph().
                                                                                     {
    for (NodeIt v(*graph); v != INVALID; ++v)
        if ((*nodeid)[v] == id) {
            *node = v;
            return true;
        }
    return false;
}
register_node_set() [1/2]
void deregnet::register_node_set (set< string > ** node_set, string comma_separated_list_of_nodes)
Definition at line 64 of file utils.cpp.
References split_string().
Referenced by parse_options(), and set_union().
                                                             {
    if (!(*node_set))
        *node_set = new set<string>(split_string(comma_separated_list_of_nodes, ","));
    else
        set_union<string>(node_set, split_string(comma_separated_list_of_nodes, ","));
}
register_node_set() [2/2]
void deregnet::register_node_set (std::set< std::string > ** node_set, std::string comma_separated_list_of_nodes)
Parse a comma-seperated list of token into a set containing the tokens.
Parameters
out node_set Resulting token set
in comma_separated_list_of_nodes Comma-seperated string of tokens
register_node_set_file() [1/2]
void deregnet::register_node_set_file (set< string > ** node_set, string path2file)
Definition at line 74 of file utils.cpp.
Referenced by parse_options(), and set_union().
                                              {
    set<string> nodes_in_file;
    try {
        ifstream file;
        file.open(path2file);
        string nodeid;
        while (!file.eof()) {
            file >> nodeid;
            nodes_in_file.insert(nodeid);
        }
        file.close();
    }
    catch (...) {
        cerr << "Could not read file " << path2file << endl;
    }
    if (!(*node_set))
        *node_set = new set<string>(nodes_in_file);
    else
        set_union<string>(node_set, nodes_in_file);
}
register_node_set_file() [2/2]
void deregnet::register_node_set_file (std::set< std::string > ** node_set, std::string path2file)
Parse contents of token file into a set containing the tokens.
Parameters
out node_set Resulting token set
in path2file Path to file, every line is considered a token
set_union()
template<typename T >
void deregnet::set_union (std::set< T > ** A, const std::set< T > & B)
Inplace set union.
Template Parameters
T Type of set elements
Parameters
in,out A First argument of union, union of A and B
   B[in] Second argument of union
Definition at line 68 of file utils.hpp.
References register_node_set(), and register_node_set_file().
                                                  {
    for (auto elmt : B) (*A)->insert(elmt);
}
split_string() [1/2]
set<string> deregnet::split_string (const string & str, const string & sep)
Definition at line 49 of file utils.cpp.
Referenced by register_node_set().
                                            {
    set<string> split;
    string::size_type start { 0 };
    string::size_type last_sep { 0 };
    while (last_sep != string::npos) {
        last_sep = str.find_first_of(sep, start);
        split.insert(str.substr(start, last_sep - start));
        start = last_sep + 1;
    }
    return split;
}
split_string() [2/2]
std::set<std::string> deregnet::split_string (const std::string & str, const std::string & sep)
Split a string into token based on some seperation token.
Parameters
str String to split
sep Seperation token
Returns
The set of corresponding tokens.
write2sif()
void deregnet::write2sif (Graph * graph, std::set< Node > & node_set, NodeMap< std::string > * nodeid, std::string path2file)
Parameters
graph
node_set
nodeid
path2file
Definition at line 135 of file utils.cpp.
References INVALID.
                                                                                                      {
    ofstream sif_file;
    sif_file.open(path2file);
    for (auto v : node_set)
        for (OutArcIt a(*graph, v); a != INVALID; ++a)
            if (node_set.find(graph->target(a)) != node_set.end())
                sif_file << (*nodeid)[v] << "\tpp\t" << (*nodeid)[graph->target(a)] << "\n";
    sif_file.close();
}