#!/usr/bin/env bash

SELFDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

GUROBI_LICENSE=${GUROBI_LICENSE:-$HOME/.licenses/gurobi}

BASEIMAGE=$1
shift

PERMISSIONS=$(stat -c "%a" $(pwd))
OWNER=$(stat -c "%U" $(pwd))
GROUP=$(stat -c "%G" $(pwd))

docker run --rm -v $(pwd):/io debian:buster-slim sh -c "chmod 777 /io"

docker run --rm -it --pid host \
		--mac-address $MAC_ADDRESS_FOR_GUROBI_DOCKER \
		-v $GUROBI_LICENSE:/gurobi/lic \
		-v $(pwd):/io \
		$BASEIMAGE $@

docker run --rm -v $(pwd):/io debian:buster-slim sh -c "chmod $PERMISSIONS /io"
docker run --rm -v $(pwd):/io debian:buster-slim sh -c "chown -R $(id -u $OWNER):$(id -g $GROUP) /io"
